### ISSUE TITLE
Unhandled Exception: RangeError (end): Invalid value: Not in inclusive range 48..372: 13893680

### ISSUE THREAD

**Issue by AnandSaran** [isar/isar#1093] opened 2023-02-10 07:23 UTC
### Steps to Reproduce

1. I have saved one model object.
2. After adding a new filed in the model class and generated new .g.dart file, then while retrieve getting below error.
Unhandled Exception: RangeError (end): Invalid value: Not in inclusive range 48..372: 13893680
3. I have added DB migration also same issue
![image](https://user-images.githubusercontent.com/13350800/218027501-a54eddb7-9ed0-45d9-8283-3073687b5f31.png)

### Code sample
Reading data using below code
![image](https://user-images.githubusercontent.com/13350800/218027739-e0acefcb-535a-49b7-9a1f-e425e6f91ac2.png)

```dart
Provide a few simple lines of code to show your problem.
```
Here im getting exception
![image](https://user-images.githubusercontent.com/13350800/218027808-08a9d54d-fdc6-49c6-a52f-640885e5dca6.png)

### Details

 - Flutter version: >=2.18.0 <3.0.0
 - Isar version: i used 3.0.5 and 3.0.6-dev.0 both version facing same issue
 - 

---

**Comment by Daniel618** [comment] 2023-02-28 14:06
I receive a similar error. When adding a new field of type List to a embedded class i receive a Range Error when reading objects.

Steps to reproduce:
1. Create a Isar collection with a embedded objects.
2. Start application.
3. Save an instance to the Isar collection.
4. Stop application.
5. Add a new field with type List<String> to the embedded object.
6. Run flutter pub run build_runner build to update .g.dart files.
7. Restart application.
8. Try and read previously saved instance from the isar collection.

[Repository that can reproduce error](https://github.com/Daniel618/AddFieldToEmbeddedClass/tree/master/lib).
Reproduce by:
1. Start application. On startup a collection (User) is initialized and one object is added to the collection.
2. Stop application.
3. Uncomment lines 10 and 14 in Vehicle.dart to add a field to the embedded object.
4. Run command flutter pub run build_runner build
5. Start application again.
This produces the error: RangeError (start): Invalid value: Not in inclusive range 0..12: 20

I have also received a similar error in another case: RangeError (index): Index out of range: index should be less than 92: 9814453

[@UsamaKarims comment](https://github.com/isar/isar/issues/727#issuecomment-1371805077) from a similar issue also looks like the same error.

**Comment by linneahol** [comment] 2023-03-09 08:46
> 

I have the same issue

**Comment by felixjunghans** [comment] 2023-03-17 12:02
Also got RangeError (length): Invalid value: Not in inclusive range 0..54: 12081152. Error thrown null. when adding two new fields to an embedded class

**Comment by simc** [comment] 2023-04-16 10:50
This is fixed in v3.1.0 which will be available soon on pub.dev.

**Closed by simc** 2023-04-16 10:50 UTC

**Comment by barees63** [comment] 2023-04-24 02:55
I'm seeing this error today with 3.1.0

this is on iOS 16.2 simulator and is occurring while deserializing an embedded class that I haven't changed recently.

```
flutter: EXCEPTION: RangeError (end): Invalid value: Not in inclusive range 107..118: 7950955
flutter: #0      RangeError.checkValidRange (dart:core/errors.dart:379:9)
flutter: #1      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1695:26)
flutter: #2      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
flutter: #3      IsarReaderImpl.readStringOrNull
```

**Comment by holotrek** [comment] 2024-02-03 08:00
I am still getting this error with v3.1.0+1

**Comment by klausszilvas** [comment] 2024-02-16 11:02
It's not solve with v3.1.0+1
Reverting changes do not help. The Database is damaged. Must delete the App and build up the Database from scratch. Not possible in production mode.

**Comment by Vedansh-Dubey** [comment] 2024-04-11 07:27
> This is fixed in v3.1.0 which will be available soon on pub.dev.

Issue is still open in v3.1.0+1... Reopen the issue

**Comment by Mistic92** [comment] 2024-04-16 12:43
I have added DateTime field to embedded class and I'm getting error `RangeError (end): Invalid value: Not in inclusive range 5..9: 131335`

**Comment by raj457036** [comment] 2024-04-16 20:04
Same! issue suddenly started getting this issue after hot reload.

**Comment by RaphKa02** [comment] 2024-11-13 11:13
same here

**Comment by ismail-go** [comment] 2024-12-17 14:50
same here!
