### ISSUE TITLE
type 'EnumElementImpl' is not a subtype of type 'ClassElement' in type cast

### ISSUE THREAD

**Issue by pikhosh** [isar/isar#719] opened 2022-09-25 02:53 UTC
### Steps to Reproduce

1. Create a Collection/Embedded object
2. Use an Enum inside that Collection/Embedded object
3. Run `flutter pub run build_runner build`

_Only Isar v3.0.1 has this problem (v3.0.0 has no problem)_

### Code sample

```dart
import 'package:isar/isar.dart';

part 'notes.g.dart';

@Collection()
class Note {
  Id id = Isar.autoIncrement;

  late String title;

  @Index()
  @Enumerated(EnumType.name)
  late NoteType type;
}

enum NoteType {
  first,
  second,
  third,
}
```

### Details

 - Platform: Windows 11
 - Flutter version: 3.3.2
 - Isar version: 3.0.1
 - build_runner version: 2.2.1

The result of `flutter pub run build_runner build -v`:

```
type 'EnumElementImpl' is not a subtype of type 'ClassElement' in type cast
package:isar_generator/src/isar_analyzer.dart 167:57        IsarAnalyzer._getEmbeddedDartNames._fillNames
package:isar_generator/src/isar_analyzer.dart 179:5         IsarAnalyzer._getEmbeddedDartNames
package:isar_generator/src/isar_analyzer.dart 55:26         IsarAnalyzer.analyzeCollection
package:isar_generator/src/collection_generator.dart 45:35  IsarCollectionGenerator.generateForAnnotatedElement
package:source_gen/src/generator_for_annotation.dart 53:30  GeneratorForAnnotation.generate
package:source_gen/src/builder.dart 352:33                  _generate

[SEVERE] Build:
Failed after 102ms
[+2949 ms] "flutter run" took 3,232ms.
[   +6 ms] pub finished with exit code 1
[   +1 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:418:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:249:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +272 ms] ensureAnalyticsSent: 266ms
[   +5 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
```

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by penhorwood** [comment] 2022-09-29 13:03
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19044.2006], locale en-US)
    • Flutter version 3.3.2 on channel stable at D:\development\flutter-sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (2 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\andrew\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\andrew\AppData\Local\Android\Sdk
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Android Studio (version 2021.2)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by ebelevics** [comment] 2022-09-29 13:19
Same issue. Migrated back to 3.0.0

**Comment by penhorwood** [comment] 2022-09-29 16:57
Upgrading to Flutter 3.3.3 which came out a few hours ago did NOT help the situation.

**Comment by tr-stan** [comment] 2022-09-30 21:36
Upgrading to Flutter 3.3.3 and rolling back to isar 3.0.0 did not work for me. Flutter doctor is totally fine, I've ran flutter clean, flutter pub cache repair, deleted pubspec, podfile, restarted my computer...all of the ritualistic steps and still it's giving me this error when it wasn't yesterday.

**Comment by penhorwood** [comment] 2022-10-01 04:13
I got this statement from the Isar Telegram group:
"I was told above to downgrade analyzer from 5.0.0 to 4.7.0, apparently that is the cause."  

I have not tried that yet.

**Comment by penhorwood** [comment] 2022-10-01 04:28
I downgrade the analyzer to 4.6.  Here is the command:

**dart pub downgrade analyzer**

https://dart.dev/tools/pub/cmd/pub-downgrade

**Comment by IsmailAbdirahman** [comment] 2022-10-02 12:21
![STolLU9B_400x400](https://user-images.githubusercontent.com/56909567/193453614-3814cbae-8128-4a3e-8f1d-f5de225109c5.jpg)

**Comment by leisim** [comment] 2022-10-02 23:56
This is fixed in the newest version.

**Closed by leisim** 2022-10-02 23:56 UTC
Labels: bug, area:generator
