### ISSUE TITLE
IsarError: Could not initialize IsarCore library for processor architecture "android_arm". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies. Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found

### ISSUE THREAD

**Issue by adn9990** [isar/isar#1096] opened 2023-02-11 18:51 UTC
IsarError: Could not initialize IsarCore library for processor architecture "android_arm". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies. Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found

in 
Samsung J2 Android Version : 6

**Comment by zigapovhe** [comment] 2023-02-11 18:56
Duplicate of https://github.com/isar/isar/issues/1095
Please check other issues before opening new one.

**Comment by adn9990** [comment] 2023-02-11 19:12
Already added dependencies still getting error

**Comment by simc** [comment] 2023-04-16 10:49
This is fixed in v3.1.0 which will be available soon on pub.dev.

**Closed by simc** 2023-04-16 10:49 UTC

**Comment by adn9990** [comment] 2023-04-23 04:48
v3.1.0 is available but its not solved

**Comment by andre-nk** [comment] 2023-04-27 09:48
> v3.1.0 is available but its not solved

Same here, got this one from Crashlytics:
IsarError: Could not initialize IsarCore library for processor architecture "android_arm". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies. Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found

**Comment by MovingMelody** [comment] 2023-05-22 05:09
> > v3.1.0 is available but its not solved
> 
> Same here, got this one from Crashlytics: IsarError: Could not initialize IsarCore library for processor architecture "android_arm". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies. Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found

Any update on this issue? Getting same error @simc

**Comment by TommyLCox** [comment] 2024-01-22 16:31
For me this was being caused by not being able to get the version number.  I resolved it by going into XCode and making this setting change:

<img width="893" alt="image" src="https://github.com/isar/isar/assets/12648015/c8fd8a31-7509-4e0f-9008-f5210d7941f3">
