### ISSUE TITLE
SIGABRT (Signal 6, Code 0)

### ISSUE THREAD

**Issue by JulianBissekkou** [isar/isar#1312] opened 2023-06-21 09:46 UTC
### Steps to Reproduce

I did my best to create reproducable steps for this but from my point of view the following issue is happening randomly. I know that those are the worst issues, but I am trying to provide as much detail as possible for you to come up with a potential fix.

Therefore I am not able to provide a reproduciable example.

The issue was caught by sentry.
<details><summary>Stacktrace</summary><blockquote>
<img width="836" alt="image" src="https://github.com/isar/isar/assets/36447137/1bcedea3-5057-4a40-bdde-e7061251c11d">
</blockquote></details>

I am not a rust expert, but are we able to attach sources to the stacktrace in order to get more information?

### Code sample

Our setup is quite easy. We have a `Repository` class that saves some kind of log messages into Isar.
As soon as the app starts we save a few objects in the database which happens regularly. We are talking about 1-5 writes per second.

Open the db:
```dart
    // Try getting the instance or open a new one if needed.
    var isar = Isar.getInstance();
    isar ??= await Isar.open(
      [MyLogMessageSchema],
      directory: dir.path,
    );
```

Persist the data using:
```dart
db.writeTxn(() => db.logMessageDBModels.put(object));
```

### Details

 - Platform: iPhone 14,5, iOS 16.5
 - Kernel Version: Darwin Kernel Version 22.5.0: Mon Apr 24 21:09:37 PDT 2023; root:xnu-8796.122.4~1/RELEASE_ARM64_T8110
 - Flutter version:  3.10.2
 - Isar version:   `isar: 3.1.0+1` / `  isar_flutter_libs: 3.1.0+1`

### Searched for duplicates but none of them fit:
#915 - Closed and issue should be fixed in v3.1.0
#462 - The issue is not happening on startup, our app was running for 6 seconds after the issue happened

**Comment by simc** [comment] 2023-06-21 13:09
Hey! Thanks for reporting and sorry for the issue.

A few questions because this is a tricky one to solve. It could really be anything.

- How many devices are affected?
- Does the issue occur frequently on the same devices?
- Did you ever experience this yourself?

How much data are you trying to store in Isar. Try reducing the `maxSizeMiB` option in `Isar.open()`. The default is 1GB but Isar 4 will reduce that to 256MB.

**Comment by simc** [comment] 2023-06-21 13:20
Please also check for a stack trace in the XCode organizer

**Comment by JulianBissekkou** [comment] 2023-06-23 05:54
>How many devices are affected?
Right now only a single device.

>Does the issue occur frequently on the same devices?
No. We had this issue only once on the device I mentioned above.

>Did you ever experience this yourself?
No, I tried to reproduce the issue on a local device but with no luck.

 
>How much data are you trying to store in Isar. Try reducing the maxSizeMiB option in Isar.open(). The default is 1GB but Isar 4 will reduce that to 256MB.
Sure :) Can you explain why this should reduce the possibility of this error happening?


>Please also check for a stack trace in the XCode organizer
<img width="1260" alt="image" src="https://github.com/isar/isar/assets/36447137/8b000698-864f-495f-b9e0-80253701e28d">

**Comment by simc** [comment] 2023-06-23 14:19
>Sure :) Can you explain why this should reduce the possibility of this error happening?

Isar uses virtual memory. Even though in theory mmap is only limited by available disk space older phones severely limit the available amount of virtual memory. Isar tries to figure out how much it can safely request from the OS but that doesn't always work. 256MB is a safe amount that is granted in almost all circumstances.

That being said I'm not sure this is an instance of a memory issue. It looks more like an actual tsar bug. Unfortunately it panics without unwrapping a stack trace so it might be hard to find without a way to reproduce. I'll keep my eyes open. Please report if you (or anyone else reading this) see more events like this 🙂

**Comment by Liloupar** [comment] 2023-06-26 02:27
> > Sure :) Can you explain why this should reduce the possibility of this error happening?
> 
> Isar uses virtual memory. Even though in theory mmap is only limited by available disk space older phones severely limit the available amount of virtual memory. Isar tries to figure out how much it can safely request from the OS but that doesn't always work. 256MB is a safe amount that is granted in almost all circumstances.
> 
> That being said I'm not sure this is an instance of a memory issue. It looks more like an actual Isar bug. Unfortunately it panics without unwrapping a stack trace so it might be hard to find without a way to reproduce. I'll keep my eyes open. Please report if you (or anyone else reading this) see more events like this 🙂

What is the relative safety range for maxSizeMiB? I have an e-book reader app.
After parsing files in formats like txt/epub, I write the content of each chapter into Isar. Therefore, when importing a large number of books, the size of the Isar database can become very large.
I would like to know: 1. Is Isar suitable for this situation, or is SQLite more appropriate? 2. Are there any potential risks in setting maxSizeMiB to 10240 or larger?
Thank you very much for providing such a useful database.
@simc

**Comment by simc** [comment] 2023-06-26 07:38
Isar is suitable for such a task. Especially since Isar v4 is almost ready and you'll be able to switch between the native Isar engine and an SQLite engine with a single line of code.

> Are there any potential risks in setting maxSizeMiB to 10240

That's 10GB. Do you have a use case where you need to store millions of eBooks simultaneously? It's likely that you have to rethink your overall design.

No mobile OS won't grant you that amount of virtual memory.
Realm and ObjectBox also rely on mmap and SQLite will experience significant slowdowns.

A common mistake I see people make is to abuse databases as a file system.

> What is the relative safety range for maxSizeMiB?

To have the maximum compatibility I'd not go higher than 1024MB

**Comment by Liloupar** [comment] 2023-06-26 09:02
> Isar is suitable for such a task. Especially since Isar v4 is almost ready and you'll be able to switch between the native Isar engine and an SQLite engine with a single line of code.
> 
> > Are there any potential risks in setting maxSizeMiB to 10240
> 
> That's 10GB. Do you have a use case where you need to store millions of eBooks simultaneously? It's likely that you have to rethink your overall design.
> 
> No mobile OS will grant you that amount of virtual memory. Realm and ObjectBox also rely on mmap and SQLite will experience significant slowdowns.
> 
> A common mistake I see people make is to abuse databases as a file system.
> 
> > What is the relative safety range for maxSizeMiB?
> 
> To have the maximum compatibility I'd not go higher than 1024MB. If you can ignore very old phones 1500-2000 will probably be fine.
> 
> Usually Isar will just mmap less space if the OS doesn't grant the full amount.

I want to import the content of the books into Isar because want to utilize the full-text indexing feature of the database.
I don't intend to store millions of books. My estimation for the size is based on approximately 500 books, assuming each book is around 10 MB. So, it would require approximately 10 * 500 = 5000 MB

**Comment by simc** [comment] 2023-06-26 11:57
10MB sounds like a lot. I have little knowledge about eBooks but a guess would be 1500 to 1800 characters per page and around 250 pages on average. Most of the text is ASCII or Latin-1 so I'd guess about 550KB of text per book.

Index sizing works a bit different because you don't need to store duplicate words. In your case a custom indexing solution is probably better than the built in FTS.

Depending on your use case I'd recommend to dynamically load and unload multiple Isar/ObjectBox/Realm instances. Alternatively you can try using SQLite but I think the performance will be suboptimal.

**Comment by Liloupar** [comment] 2023-06-26 12:22
> Millions is an exaggeration lol but 10MB sounds like a lot. I have little knowledge about eBooks but a guess would be 1500 to 1800 characters per page and around 250 pages on average. Most of the text is ASCII or Latin-1 so I'd guess about 550KB of text per book.
> 
> Index sizing works a bit different because you don't need to store duplicate words. In your case a custom indexing solution is probably better than the built in FTS.
> 
> Depending on your use case I'd recommend to dynamically load and unload multiple Isar/ObjectBox/Realm instances. Alternatively you can try using SQLite but I my guess is the performance will be suboptimal.
> 
> I don't know anything about your project but personally I'd avoid indexing more than 50 books. Maybe try finding a way to figure out the users favorite/most important books. If that's not an option consider outsourcing the indexing to a server. Doing that kind of work on a battery powered device with limited resources is unlikely to be a good idea.

Thank you very much. I think I understand what to do now.

**Comment by huntrist** [comment] 2023-07-17 16:08
> To have the maximum compatibility I'd not go higher than 1024MB. If you can ignore very old phones 1500-2000 will probably be fine.
> 
> Usually Isar will just mmap less space if the OS doesn't grant the full amount.

I have a similar siutation (requiring larger than 2GB DB), what did you end up with?

**Comment by huntrist** [comment] 2023-07-17 16:15
> Isar is suitable for such a task. Especially since Isar v4 is almost ready and you'll be able to switch between the native Isar engine and an SQLite engine with a single line of code.
> 
> >

Does this mean Isar v4 can use sqlite to store objects, and be no longer limited by the 2GB virtual memory?

**Comment by simc** [comment] 2023-08-01 19:13
>Does this mean Isar v4 can use sqlite to store objects, and be no longer limited by the 2GB virtual memory?

Yes

**Comment by simc** [comment] 2023-08-16 11:10
This is most likely fixed in Isar v4. Please reopen if it still occurs

**Closed by simc** 2023-08-16 11:10 UTC
