### ISSUE TITLE
Flutter exits with error when starting using flutter run

### ISSUE THREAD

**Issue by Coinmaster123456** [isar/isar#585] opened 2022-08-24 19:43 UTC
Flutter gives back these error when trying to launch isar 3.0.0-dev.8 in a web app
Desktop and Mobile compile just fine and also run like normal
![image](https://user-images.githubusercontent.com/70707774/186508586-31fe0ef3-9131-4f7a-b14f-93fc8b1a7ebc.png)

**Comment by leisim** [comment] 2022-08-24 20:01
Flutter web is not supported in 3.0.x yet.

Duplicate of #535

**Closed** 2022-08-24 20:01 UTC
