### ISSUE TITLE
Latest version of Isar generator is not compatible with latest version of bloc_test

### ISSUE THREAD

**Issue by PoloLacoste** [isar/isar#277] opened 2022-03-02 15:58 UTC
**Steps to Reproduce**
- Adding latest version of `bloc_test` (9.0.3)
- Adding latest version of `isar_generator` (2.2.1)
- `flutter pub get`

**Code sample**
```
[my_app] flutter pub get
Running "flutter pub get" in my_app...             
Because test >=1.16.0-nullsafety.19 <1.16.6 depends on test_api 0.2.19 and test >=1.16.6 <1.17.10 depends on analyzer ^1.0.0, test >=1.16.0-nullsafety.19 <1.17.10 requires test_api 0.2.19 or analyzer ^1.0.0.
And because test >=1.17.10 <1.20.0 depends on analyzer >=1.0.0 <3.0.0, test >=1.16.0-nullsafety.19 <1.20.0 requires test_api 0.2.19 or analyzer >=1.0.0 <3.0.0.
And because test >=1.20.0 depends on test_api 0.4.9 and isar_generator >=2.0.0-dev.0 depends on analyzer ^3.0.0, if isar_generator >=2.0.0-dev.0 and test >=1.16.0-nullsafety.19 then test_api 0.2.19 or 0.4.9.
And because bloc_test 9.0.3 depends on test ^1.16.0 and no versions of bloc_test match >9.0.3 <10.0.0, if isar_generator >=2.0.0-dev.0 and bloc_test ^9.0.3 then test_api 0.2.19 or 0.4.9.
And because my_app depends on flutter_test from sdk which depends on test_api 0.4.8, isar_generator >=2.0.0-dev.0 is incompatible with bloc_test ^9.0.3.
So, because my_app depends on both bloc_test ^9.0.3 and isar_generator ^2.2.1, version solving failed.
pub get failed (1; So, because my_app depends on both bloc_test ^9.0.3 and isar_generator ^2.2.1, version solving failed.)
exit code 1
```

**Version**
 - Platform: Android
 - Flutter version: 2.10.2
 - Isar version: 2.2.1
 - Isar Generator version: 2.2.1

I don't really know if I should open this issue on the BloC git repository (@felangel 👋) or here.

**Comment by felangel** [comment] 2022-03-02 16:20
Duplicate of https://github.com/felangel/bloc/issues/3110

**Comment by alarkirikal** [comment] 2022-03-11 07:25
@felangel The possible solution there to install a downgraded version of `freezed` does not work though - I have a similar issue where it's not possible to add `isar_generator` to the project because we're using `test: any`
```
depends on both isar_generator ^2.2.1 and test any, version solving failed
```

**Comment by mafejzuli** [comment] 2022-03-13 12:43
A temporary solution could be to override the analyzer dependency with:
```yaml
dependency_overrides:
  analyzer: ^3.0.0
```
At least my tests still work fine.

**Comment by leisim** [comment] 2022-05-15 20:19
This should be fixed now 🙂

**Closed by leisim** 2022-05-15 20:19 UTC
Labels: enhancement, dart
