### ISSUE TITLE
thread 'isarworker' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownIndex', packages\isar_core\src\collection.rs:374:49

### ISSUE THREAD

**Issue by AbdulHaseeeb** [isar/isar#847] opened 2022-10-31 06:58 UTC
```
import 'package:isar/isar.dart';
part 'todo_model.g.dart';

@collection
class Todo {
  String id;

  Id get isarId => fastHash(id);

  bool completed;

  String description;

  @Index()
  late int seqCount;

  int count = 0;

  Todo({required this.id, required this.description, this.completed = false}) {
    this.seqCount = ++count;
  }
}

int fastHash(String string) {
  var hash = 0xcbf29ce484222325;

  var i = 0;
  while (i < string.length) {
    final codeUnit = string.codeUnitAt(i++);
    hash ^= codeUnit >> 8;
    hash *= 0x100000001b3;
    hash ^= codeUnit & 0xFF;
    hash *= 0x100000001b3;
  }

  return hash;
}

///string to int with hashFunction
int stringToIntHash(String string) {
  return fastHash(string);
}

```

**Comment by AbdulHaseeeb** [comment] 2022-10-31 07:02
I'm trying to index this Todo By seqCount. With int Ids from String Ids database misarrange todos, the first one goes to 5th no, 5th to 7th etc.

**Comment by MAShah-UK** [comment] 2022-11-07 20:18
Not sure if it's related, but I had a similar error message and managed to fix it (I think) by clearing the db.
Maybe when you create/open a new schema the indexes go out of sync and Isar throws an error.

**Comment by leisim** [comment] 2022-11-08 12:02
Duplicate of #795

**Closed by leisim** 2022-11-08 12:02 UTC
