### ISSUE TITLE
Isar Inspector on Windows

### ISSUE THREAD

**Issue by richard457** [isar/isar#237] opened 2022-02-14 16:52 UTC
How to install  Isar Inspector  on windows

**Comment by leisim** [comment] 2022-02-14 17:11
It's a Flutter app, you can run it from source. Unfortunately I didn't have time to automate and test the build in the CI.

A PR would be greatly appreciated if you'r interested 🙂

**Comment by richard457** [comment] 2022-02-14 18:10
sure, will look at it in my free time.

**Comment by CodeDoctorDE** [comment] 2022-02-18 13:03
Duplicate of #90 ?

**Comment by leisim** [comment] 2022-02-18 13:04
@CodeDoctorDE Oh yes, thanks!

**Closed by leisim** 2022-02-18 13:04 UTC
Labels: enhancement
