### ISSUE TITLE
put 19 digits number to isar, isar will store wrong value

### ISSUE THREAD

**Issue by weishirongzhen** [isar/isar#1311] opened 2023-06-21 08:43 UTC
### Steps to Reproduce

if I put this int  1,111,111,111,111,111,111 number to isar, isar store as wrong value 1,111,111,111,111,111,200, 
and it's smaller than 9,223,372,036,854,775,807
also other value with 19 digits number will cause same result, the last three number will store to "000" or "200" atleast

### Code sample

```dart
 isarService.isar.writeTxn(() {
      return isarService.isar.testDaos.put(TestDao()..num = 1111111111111111111);
    });

```
<img width="1110" alt="image" src="https://github.com/isar/isar/assets/54241621/b8eefafe-6407-45fb-a56e-6161c2128c7f">

### Details

 - Platform: any 
 - Flutter version: [3.10.0]
 - Isar version: [3.1.0+1]

---

 - [ x ] I searched for similar issues already
 - [ x ] I filled the details section with the exact device model and version
 - [ x ] I am able to provide a reproducible example

**Comment by simc** [comment] 2023-08-01 18:59
duplicate of #772

**Closed** 2023-08-01 19:08 UTC
