### ISSUE TITLE
Web not building

### ISSUE THREAD

**Issue by kulture-rob-snider** [isar/isar#656] opened 2022-09-09 13:32 UTC
**Steps to Reproduce**
When trying to run for web, several errors are thrown. When I fork the repo, `packages/isar/lib/src/web` shows a lot of errors.

**Code sample**
```
import 'package:flutter/material.dart';
import 'package:isar/isar.dart';

part 'main.g.dart';

@collection
class Email {
  Id id = Isar.autoIncrement;

  String? emailAddress;
}

void main() async {
  await Isar.open([EmailSchema]);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: Text('Flutter Demo Home Page'),
    );
  }
}
```

**Version**
 - Platform: Web
 - Flutter version: 3.0.5
 - Isar version: 3.0.0-dev.14
 - Isar Generator version: 3.0.0-dev.14

**Comment by muddassar-lab** [comment] 2022-09-09 15:01
In the current dev version, the Web platform is not supported.

**Comment by leisim** [comment] 2022-09-11 23:16
Duplicate of #535

**Closed by leisim** 2022-09-11 23:16 UTC
