### ISSUE TITLE
32-bit devices: Unhandled Exception: IsarError: Cannot open Environment

### ISSUE THREAD

**Issue by zexross** [isar/isar#187] opened 2022-01-14 06:42 UTC
**Steps to Reproduce**
Got an exception when trying to run `isar.open`

```
E/flutter ( 7883): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: IsarError: Cannot open Environment
E/flutter ( 7883):
```

**Code sample**
```
 var dbPath = (await getApplicationDocumentsDirectory()).path;
      
final isar = await Isar.open(
  schemas: [dbSchema],
  directory: dbPath,
);
```

**Version**
 - Platform: Android 11
 - Flutter version: 2.8.1
 - Isar version: 2.0.0-dev.0
 - Isar Generator version: 2.0.0-dev.0

**Comment by leisim** [comment] 2022-01-14 06:45
@zexross Are you sure the path you provided exists?

**Comment by zexross** [comment] 2022-01-14 07:31
@leisim Thank you for the quick response:)

Yeah! I think so.

 I took the path from `(await getApplicationDocumentsDirectory()).path`. And confirmed if the directory exists by printing the dir variable shown below:
```
bool dir = await Directory(databasePath).exists();
print('dir: $dir');
```
On printing `dbpath` in the code sample provided. I received the below output in the console:
```
data/user/0/com.example.sample_app/app_flutter
```

Let me know if I am missing anything here!

**Comment by leisim** [comment] 2022-01-14 07:36
@zexross I just published a new release that should return more information why opening the environment fails. Would be awesome if you could share the output.

**Comment by zexross** [comment] 2022-01-14 07:43
@leisim I upgraded the dependencies and tried the app again. Sharing the output here:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: IsarError: Cannot open Environment: MdbxError (22): Invalid argument
```

**Comment by leisim** [comment] 2022-01-14 07:46
Thanks @zexross this seems to be the same issue as #173. Would it be possible to share an example that causes this? Or does it happen with the sample app?

**Comment by zexross** [comment] 2022-01-14 08:34
@leisim No, it's not happening with the sample app. I will soon try to test with the sample app from my side though.

I am sharing the schema class:
```
@Collection()
class DeviceData {
  @Id()
  int? id;
  @Index(unique: true)
  late String stringId;
  @Index(type: IndexType.hash)
  late String secondaryId;
  late bool isTrendData;
  late int lifespan;
  late int reading;
  @Index()
  late int date;
  late int timezoneOffsetInMinutes;
}
```

After running the code generator using `flutter pub run build_runner build`. After the app when `Isar.open` is called the mentioned exception is thrown. I am sharing the exact code used for invoking it as well:

```
var databasePath = (await getApplicationDocumentsDirectory()).path;

final isar = await Isar.open(
  schemas: [DeviceDataSchema],
  directory: databasePath,
);
```

Also, I am sharing all the related plugins that I used:
```
dependencies:
  isar: ^2.0.0-dev.1
  isar_flutter_libs: ^2.0.0-dev.1

dev_dependencies:
  isar_generator: ^2.0.0-dev.1
  build_runner: ^2.1.7
```

Hope these details help. Let me know if any other details are needed from my end that can help :)

**Comment by zexross** [comment] 2022-01-14 09:20
Hello @leisim ,

I tried testing it on the [Sample App](https://github.com/isar/samples) on two physical android phones that I have. These are my finding: 

- It worked for Android 11 and failed for Android 10 with the same issue. This is the same time when I realised that I mentioned the wrong android version while opening the issue. I realised this when I tested it with my other smartphone. Really sorry for that!
- I also tried to test the earlier shared example on both versions. It is running fine on Android 11 but throwing the exception on Android 10.

Sorry again wrong platform version mention from my side.

**Comment by leisim** [comment] 2022-01-14 10:22
@zexross Thanks so much for your awesome help! Unfortunately I still fail to reproduce it with a debug build of the sample app.

I tried:
- Android 10 emulator (arm64)
- Android 10 Samsung device
- Android 10 Xiaomi device
- Android 9 Xiaomi device

All of them worked without issue...

**Comment by zexross** [comment] 2022-01-14 10:45
@leisim That's interesting. If possible, can you try the below mentioned or similar specs as well 🙂:

-  SM J710F (Samsung Galaxy J7 mobile) | 3100f3f3ad7313cd | android-arm | Android 8.1.0 (API 27) 
- MOA LX9N (Honor 9 mobile) | LSDBB20629207194 | android-arm | Android 10 (API 29)

These are the outputs from `flutter doctor -v`

Thanks a lot for putting in this much effort. Really appreciate it. And do let me know if I can help you in any way to figure out the bug.

**Comment by leisim** [comment] 2022-01-14 15:51
I could reproduce it on a Samsung Galaxy J7 🎉 thanks again! working on a fix now

**Comment by leisim** [comment] 2022-01-14 16:53
Seems to be an libmdbx error. I opened an issue https://github.com/erthink/libmdbx/issues/262

**Comment by andj207** [comment] 2022-01-15 14:20
It happens on my iPhone 5S too. It crashes on every first launch of the app and then works well. The error is as below (from Crashlyrics):

    Crashed: Thread
    0  libsystem_platform.dylib       0x8590 _platform_memset + 32
    1  isar_flutter_libs              0x11c5b0 mdbx_env_open + 1172
    2  isar_flutter_libs              0x465b0 isar_core::instance::IsarInstance::open_internal::h90ccdd5b072ea1b7 + 596
    3  isar_flutter_libs              0x9378 _$LT$F$u20$as$u20$threadpool..FnBox$GT$::call_box::h34872a4952decded + 948
    4  isar_flutter_libs              0x92c80 std::sys_common::backtrace::__rust_begin_short_backtrace::hb3bf5f86d8ac65d6 + 1608
    5  isar_flutter_libs              0x923c4 core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hfa83b65bfc57a1f3 + 304
    6  isar_flutter_libs              0x90060 std::sys::unix::thread::Thread::new::thread_start::h4535596ead13a3c1 + 331 (alloc.rs:331)
    7  libsystem_pthread.dylib        0xb2c0 <redacted> + 128
    8  libsystem_pthread.dylib        0xb220 _pthread_start + 44
    9  libsystem_pthread.dylib        0xecdc thread_start + 4

My code:
    
    final dbDir = await getApplicationSupportDirectory();
        _isarDb = await Isar.open(
          schemas: [DataSchema],
          directory: dbDir.path,
        );

Isar version: 2.0.0-dev.0
Isar Generator version: 2.0.0-dev.0

**Comment by ozzfelipe** [comment] 2022-01-26 18:26
I got the same error here. Is there any solution for this?

Devices with problem:
SM A01 | 32-bit | Android GO 10

**Comment by spatialbits** [comment] 2022-02-01 17:42
Also experiencing this on Samsung SM T580 tablet with Isar 2.1.0.

**Comment by leisim** [comment] 2022-02-03 10:23
@spatialbits Some older devices run a 32-bit Android version even if the processor is capable of 64-bit :(

**Comment by prakharb10** [comment] 2022-02-04 06:10
Hi @leisim 
Not sure if this is the right place to report this or should I open a new issue but I'm facing a similar error when trying to run my app on Pixel 4a API 30 (x86) emulator. The error raised is:
`Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found
`
I have added `isar_flutter_libs` to the pubspec file and the app works fine on my external device.

**Comment by leisim** [comment] 2022-02-04 06:43
@prakharb10 do you use tle latest isar version?

**Comment by prakharb10** [comment] 2022-02-04 06:46
Yes, I'm using version ^2.1.4

**Comment by florian-lefebvre** [comment] 2022-02-08 20:45
I'm facing the same issue with isar `2.1.4` on a Samsung Galaxy A10 (Android 11).
What can be done to solve this problem? Tell me if I can help you by doing tests or providing more information.
FYO the app is at https://github.com/EduWireApps/ynotes.

**Comment by florian-lefebvre** [comment] 2022-02-11 20:27
Hi @leisim sorry for the ping but supporting 32 bit devices seems (and is for me) quite important and don't know if you were notified of my last comment. This issue is currently preventing our organization from publishing the app.

**Comment by leisim** [comment] 2022-02-12 08:21
@florian-lefebvre It is not resolved yet. https://github.com/isar/isar/issues/187#issuecomment-1013291658

**Comment by electrooz** [comment] 2022-02-22 20:07
Getting the same on Alcatel 1 5033X | Android 8.1 Oreo (Go edition) | Cortex-A53. Hopefully it's fixed soon.

**Comment by richard457** [comment] 2022-02-23 18:29
I posted this https://github.com/isar/isar/issues/268 without consulting this here, so closing other one.

**Comment by JsonLinesCode** [comment] 2022-02-24 17:08
Looks like there is a new libmdbx release🤞

**Comment by spatialbits** [comment] 2022-02-24 17:23
Yeah he specifically mentions @leisim in it. Looks promising :)

**Comment by richard457** [comment] 2022-02-24 18:52
We can't wait, can't release my app now because of this error.

**Comment by jpolstre** [comment] 2022-03-02 14:22
Thanks for this work, is there any progress to fix this error?

**Comment by richard457** [comment] 2022-03-04 02:11
> Thanks for this work, is there any progress to fix this error?

@leisim any progress?

**Comment by electrooz** [comment] 2022-03-04 17:35
The issue has been closed so I assume no progress. https://github.com/erthink/libmdbx/issues/262

**Comment by spatialbits** [comment] 2022-03-04 18:07
@electrooz I could be wrong but I suspect the fix was done in https://github.com/erthink/libmdbx/issues/267

**Comment by electrooz** [comment] 2022-03-04 18:31
I think that's only for iOS. @spatialbits

**Comment by spatialbits** [comment] 2022-03-04 18:36
Yeah but it seemed to be related to setting the memory geometry size or something, which seemed to be related to both issues. I dunno though, I _should_ know how how libmdbx work but I don't reallly.

**Comment by electrooz** [comment] 2022-03-04 20:46
Was I supposed to change my version in `pubspec.yaml`? I'm on `2.2.1`.

I'm still getting the same issue on an Alcatel 1 5033X.

```
IsarError (IsarError: Cannot open Environment: MdbxError (22): Invalid argument)
```

**Comment by JsonLinesCode** [comment] 2022-03-15 11:34
Hey, no news about this for quite a while, anyone made a fork fixing the issue by updating the dependencies or could make it ?

**Comment by JPM84** [comment] 2022-03-17 17:00
IsarDB ist really great but no support for 32-bit Android is kind of the only thing holding us back from using it more.
Sadly, many older or low-end Android-Devices still use versions like Android GO or 32-bit chips.
What is needed to reopen/find the issue [libmdbx/#262](https://github.com/erthink/libmdbx/issues/262)?
I could provide "Samsung Galaxy S5 Mini (32-bit Device)" or a "Nokia 1.3 (Android GO 32-bit)".

**Comment by anandsubbu007** [comment] 2022-03-18 12:30
Any update?

**Comment by jeremylcarter** [comment] 2022-04-03 23:28
I am also interested in supporting 32 bit Android devices.

**Comment by adhy57** [comment] 2022-04-06 09:07
Any update?

**Comment by tijanirf** [comment] 2022-04-12 12:37
> We can't wait, can't release my app now because of this error.

Just release the app that is using Isar to the play store, i hope i found this issue earlier. Unlucky me i guess 😅

I hope the fix will be released soon, i do really like Isar for all its features and it is kind of expensive to migrate to the new database.

**Comment by seanradford** [comment] 2022-04-14 08:14
I'm sure this does not help, but I'm seeing this on a Nokia 1.3 Android Go:

androidId: bc4634c0b3b598fd
bootloader: unknown
display: 00WW_2_280_SP03
fingerprint: Nokia/Drax_00EEA/DRX:11/RKQ1.200928.002/00WW_2_28C:user/release-keys
hardware: qcom
host: Hoki_192-168-151-90_15527_docker
manufacturer: HMD Global
model: Nokia 1.3
versionBaseOs: Nokia/Drax_00EEA/DRX:11/RKQ1.200928.002/00WW_2_280:user/release-keys
versionCodename: REL
versionIncremental: 00WW_2_28C
versionPreviewSdk: 0
versionRelease: 11
versionSdk: 30
versionSecurityPatch: 2021-10-05

And a similar experience (but fatal crash on every app start) with an iPhone 5S - but have not been able to pull a crash report yet.

**Comment by anandsubbu007** [comment] 2022-04-16 07:19
Any update on this issue?

**Comment by TheDevManIT** [comment] 2022-04-18 16:00
I checked in Emulator (64bit and 32bit) when try to run with 32bit emulator i'm getting same error.

**Comment by jpolstre** [comment] 2022-04-19 00:13
It's a fantastic package, I look forward to any news to fix this issue, but it's been a long time. so I'm seriously thinking of using: [https://docs.objectbox.io/](url)

**Comment by seanradford** [comment] 2022-04-19 08:21
The Isar project in general may also be affected by the libmdbx repository no longer existing... https://github.com/erthink/libmdbx/

**Comment by leisim** [comment] 2022-04-19 08:22
@seanradford Not really, the repo just moved here: https://gitflic.ru/project/erthink/libmdbx

**Comment by spatialbits** [comment] 2022-04-19 16:10
Does the libmdbx move to gitflic concern anyone else or is it just me? There's a [single issue](https://gitflic.ru/project/erthink/libmdbx/issue/1) in the new repo:

_(google translated)_
1. A pause of three days in case github recognizes its actions as erroneous and gives at least some guarantees that this will not happen again in the future. Of course, this is approximately unbelievable, but not excluded. So I will wait three days.
2. In three days, the transition to a sovereign regime of support and development of projects:
   - a complete moratorium on the use of infrastructure and/or technologies outside the jurisdiction of Russia or Belarus (the Union State), but without restrictions on access from outside;
   - elimination of all mentions, links, dependencies of technological files, etc. associated with compromised/failed infrastructure;
   - gradual translation of the development into Russian (including new documentation and comments in the code), but with the provision of machine translation and without targeted translation of existing documentation and comments in the code.
3. Support for own CI and auxiliary hosting (generated documentation, CI status badges, etc.).
gradual implementation of non-public CI on own resources/servers;
at least a temporary suspension of CI for Windows and OSX until they can be officially legally used;
all the rest.

Don't suppose there are any drop-in alternatives to libmdbx? Maybe this is better suited to a discussion thread.

**Comment by leisim** [comment] 2022-04-19 16:14
I also very much dislike his attitude but not much we can do at this point tbh. We could move to lmdb but it would be a breaking change (the two are incompatible).

My vote goes to continue using libmdbx but I'm open for other ideas 🙂

**Comment by spatialbits** [comment] 2022-04-19 16:48
I'd be curious to see what the other ppl using isar think. Personally I'd would lean towards lmdb as it would appear to be non-political and hosted on a more mainstream platorm. Moving mdbx to gitflic and going full russian I don't think bodes well for future development and adoption.

All that said, I have no idea of the work involved in swapping it for lmdb, or what the migration process would be for folks who have already published production builds - I've held mine back pending the 32-bit fixes so switching is no problem for us at this point.

**Comment by blaugold** [comment] 2022-04-19 16:53
Forking libmdbx is another option, if the license permits, but that might be even more work.

**Comment by leisim** [comment] 2022-04-19 17:21
Please continue the discussion here: https://github.com/isar/isar/issues/342

**Comment by richard457** [comment] 2022-04-19 19:09
> flic

Why the guy is the bad guy here? isn't Github who made a mistake and removed his repo from GITHUB or I am missing something?

**Comment by leisim** [comment] 2022-04-24 09:20
This issue should be fixed in the latest release. Could someone please confirm that it is working? 🙂🙌

**Closed by leisim** 2022-04-24 09:20 UTC
Labels: bug

**Comment by richard457** [comment] 2022-04-24 09:59
@leisim I can confirm that it is now working on 32 bit device.

**Comment by zexross** [comment] 2022-04-24 10:18
I tried on the sample app with the latest release and I am getting this new error:
```
Exception has occurred:
IsarError (IsarError: Could not initialize IsarCore library. If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.)
```
I have included the `isar_flutter_libs: ^2.4.0` package in dependency. Let me know if this is any mistake from my end only.

All the isar dependencies included in the project:
```
dependencies:
  isar: ^2.4.0
  isar_flutter_libs: ^2.4.0 

dev_dependencies:
  isar_generator: ^2.4.0
  build_runner: any
```

**Comment by richard457** [comment] 2022-04-24 10:20
> I tried on the sample app with the latest release and I am getting this new error (on Emulator):
> 
> ```
> Exception has occurred:
> IsarError (IsarError: Could not initialize IsarCore library. If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.)
> ```
> 
> I have included the `isar_flutter_libs: ^2.4.0` package in dependency. Let me know if this is any mistake from my end only.
> 
> All the isar dependencies included in the project:
> 
> ```
> dependencies:
>   isar: ^2.4.0
>   isar_flutter_libs: ^2.4.0 
> 
> dev_dependencies:
>   isar_generator: ^2.4.0
>   build_runner: any
> ```

did you run: flutter packages pub run build_runner build --delete-conflicting-outputs

**Comment by leisim** [comment] 2022-04-24 10:21
@zexross could you please share:
- Your host OS
- the emulator Android version
- emulator architecture

**Comment by zexross** [comment] 2022-04-24 10:28
> did you run: flutter packages pub run build_runner build ?

Yeah. I did


>Your host OS
the emulator Android version
emulator architecture

Sorry, should have shared this information earlier but didn't. In the hope of saving some words (some keyboard issue!)

- Host OS: Linux (Ubuntu)
- Emulator Android Version: Android 11 Google Play (API 30)
- Emulator architecture: x86

**Comment by leisim** [comment] 2022-04-24 10:36
Unfortunately Isar still doesn't support x86 **emulators**. We need to wait for the next major Flutter release (and Dart 2.17) to support them.

Isar does work on all Armv7 (32-bit) devices however.

**Comment by blaugold** [comment] 2022-04-24 10:40
Just out of interest, what's the change in Flutter that is needed for Isar on x86 emulators?

**Comment by zexross** [comment] 2022-04-24 10:41
Thanks for the info. I will check on the supported devices then and will inform here if any comes up that might need the attention. 

Thanks for all the quick responses and help :)

**Comment by leisim** [comment] 2022-04-24 11:12
@blaugold Dart 2.17 finally allows processor architecture detection. We can then also support Windows and Linux x86

**Comment by blaugold** [comment] 2022-04-24 11:18
`AbiSpecificInteger` is already available in dart `2.16.0` and c types are available in [`package:ffi`](https://github.com/dart-lang/ffi/blob/master/lib/src/c_type.dart), though the c types will also be available from `dart:ffi` in Dart `2.17.0`.

**Comment by leisim** [comment] 2022-04-24 12:18
Oh wow you are right! Why did they put it in 2.17 in the changelog? I'll work on x86 support right now!

**Comment by blaugold** [comment] 2022-04-24 12:21
> Why did they put it in 2.17 in the changelog?

I think the mappings for c types on the different architectures just weren't ready when `2.16.0` was published.

**Comment by ductranit** [comment] 2022-10-24 04:59
Hi @leisim ,
I still got this issue from latest version 3.0.2
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: IsarError: Cannot open Environment: MdbxError (11): Try again. Error thrown null.
       at FirebaseCrashlytics.recordError(firebase_crashlytics.dart:120)
       at main.<fn>(main.dart:66)
       at CrashReport.executeInZoned.<fn>(crash_report.dart:54)
```
It happens on few devices from crashlytics and I can't reproduce it on my devices.
Crashed devices: 
```
Galaxy Note10+
Galaxy A02s
Galaxy A71 5G
skythtek  816TPC
OPPO CPH2273
OPPO CPH2185
Xiaomi Redmi Note 8 Pro
```
My flutter doctor
```
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-arm, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.64.0)
[✓] VS Code (version 1.72.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

**Comment by KumarArab** [comment] 2023-01-19 08:55
I am on version 3.0.5. 
still getting this error for 32 bit devices on release mode

**Comment by ahmeedev** [comment] 2024-01-02 13:07
i faced this error on windows and macos
for windows: i delete the isar database folder seems like it got glitched so simply restart your pc
for macos: i changed the backslashes with forward slash and it work
