### ISSUE TITLE
Bad state: No element. (final properties not supported)

### ISSUE THREAD

**Issue by DarkHeros09** [isar/isar#39] opened 2021-03-27 12:21 UTC
Hi

I'm getting this error when i run the build_runner, i don't know if I'm doing something wrong here, or there's an issue.

**Error log sample**
```
[SEVERE] isar_generator:resolver on lib/app/data/models/product/product_model.dart:

Bad state: No element
dart:collection                                       ListMixin.firstWhere
package:isar_generator/src/isar_analyzer.dart 297:33  IsarAnalyzer.analyzeObjectIndex
package:isar_generator/src/isar_analyzer.dart 91:21   IsarAnalyzer.generateObjectInfo
package:isar_generator/src/isar_analyzer.dart 26:21   IsarAnalyzer.build.<fn>
dart:core                                             Iterable.toList
package:isar_generator/src/isar_analyzer.dart 27:10   IsarAnalyzer.build
```
**Steps to Reproduce**
Product_model.dart
```
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:isar/isar.dart';

import '../../../domain/entities/product.dart';
import '../product_color/product_color_model.dart';

part 'product_model.g.dart';

@Collection()
class ProductModel extends Product {
  @Id()
  final int? id;
  final String? brand;
  @Index(indexType: IndexType.words, caseSensitive: false)
  final String? name;
  final String? price;
  final String? priceSign;
  final String? currency;
  final String? imageLink;
  final String? productLink;
  final String? websiteLink;
  final String? description;
  final double? rating;
  final String? category;
  final String? productType;
  final List<String>? tagList;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final String? productApiUrl;
  final String? apiFeaturedImage;
  final List<ProductColorModel>? productColors;
  const ProductModel({
    this.id,
    this.brand,
    this.name,
    this.price,
    this.priceSign,
    this.currency,
    this.imageLink,
    this.productLink,
    this.websiteLink,
    this.description,
    this.rating,
    this.category,
    this.productType,
    this.tagList,
    this.createdAt,
    this.updatedAt,
    this.productApiUrl,
    this.apiFeaturedImage,
    this.productColors,
  }) : super(
          id: id,
          brand: brand,
          name: name,
          price: price,
          priceSign: priceSign,
          currency: currency,
          imageLink: imageLink,
          productLink: productLink,
          websiteLink: websiteLink,
          description: description,
          rating: rating,
          category: category,
          productType: productType,
          tagList: tagList,
          createdAt: createdAt,
          updatedAt: updatedAt,
          productApiUrl: productApiUrl,
          apiFeaturedImage: apiFeaturedImage,
          productColors: productColors,
        );

  factory ProductModel.fromJson(Map<String, dynamic> json) =>
      _$ProductModelFromJson(json);
  Map<String, dynamic> toJson() => _$ProductModelToJson(this);
}

```

which is extended from product
```
import 'package:equatable/equatable.dart';

import 'product_color.dart';

class Product extends Equatable {
  final int? id;
  final String? brand;
  final String? name;
  final String? price;
  final String? priceSign;
  final String? currency;
  final String? imageLink;
  final String? productLink;
  final String? websiteLink;
  final String? description;
  final double? rating;
  final String? category;
  final String? productType;
  final List<String>? tagList;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final String? productApiUrl;
  final String? apiFeaturedImage;
  final List<ProductColor>? productColors;

  const Product({
    this.id,
    this.brand,
    this.name,
    this.price,
    this.priceSign,
    this.currency,
    this.imageLink,
    this.productLink,
    this.websiteLink,
    this.description,
    this.rating,
    this.category,
    this.productType,
    this.tagList,
    this.createdAt,
    this.updatedAt,
    this.productApiUrl,
    this.apiFeaturedImage,
    this.productColors,
  });

  @override
  List<Object> get props {
    return [
      id!,
      brand!,
      name!,
      price!,
      priceSign!,
      currency!,
      imageLink!,
      productLink!,
      websiteLink!,
      description!,
      rating!,
      category!,
      productType!,
      tagList!,
      createdAt!,
      updatedAt!,
      productApiUrl!,
      apiFeaturedImage!,
      productColors!,
    ];
  }
}

```

**Version**
 - Platform: Windows
 - Flutter version: 2.0.3
 - Isar version: 0.20
 - Isar Generator version: 0.2.0

**Comment by leisim** [comment] 2021-03-27 12:46
@DarkHeros09 Could you please rerun the generator with the `-v` argument and post the error here?

**Comment by DarkHeros09** [comment] 2021-03-27 12:50
flutter pub run build_runner build --verbose --delete-conflicting-outputs

```
[  +92 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +112 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[   +1 ms] executing: [C:\flutter/] git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[  +93 ms] Exit code 0 from: git tag --points-at 4d7946a68d26794349189cf21b3f68cc6fe61dcb
[   +1 ms] 2.0.3
[  +47 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +71 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +70 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +109 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +74 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +95 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +67 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +15 ms] Using C:\flutter\.pub-cache for the pub cache.
[   +1 ms] executing: C:\flutter\bin\cache\dart-sdk\bin\pub.bat run build_runner build -v
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 431ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 127ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 1.3s

[INFO] Build:Running build...
[INFO] Heartbeat:1.0s elapsed, 0/1 actions completed.
[INFO] Heartbeat:3.1s elapsed, 0/1 actions completed.
[FINE] freezed:freezed on lib/app/data/models/product/product_model.dart:Running FreezedGenerator
[INFO] Heartbeat:4.4s elapsed, 1/6 actions completed.
[INFO] Heartbeat:5.5s elapsed, 1/6 actions completed.
[INFO] Heartbeat:6.5s elapsed, 1/6 actions completed.
[SEVERE] isar_generator:resolver on lib/app/data/models/product/product_model.dart:

Bad state: No element
dart:collection                                       ListMixin.firstWhere
package:isar_generator/src/isar_analyzer.dart 297:33  IsarAnalyzer.analyzeObjectIndex
package:isar_generator/src/isar_analyzer.dart 91:21   IsarAnalyzer.generateObjectInfo
package:isar_generator/src/isar_analyzer.dart 26:21   IsarAnalyzer.build.<fn>
dart:core                                             Iterable.toList
package:isar_generator/src/isar_analyzer.dart 27:10   IsarAnalyzer.build

[INFO] Heartbeat:19.0s elapsed, 5/6 actions completed.
[FINE] json_serializable:json_serializable on lib/app/data/models/product/product_model.dart:Running JsonSerializableGenerator - 1 of 2
[FINE] json_serializable:json_serializable on lib/app/data/models/product/product_model.dart:Running JsonLiteralGenerator - 2 of 2
[INFO] Build:Running build completed, took 19.2s

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 70ms

[SEVERE] Build:
Failed after 19.3s
[+23999 ms] "flutter run" took 24,121ms.
[   +9 ms] pub finished with exit code 1
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:364:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:238:5)
           <asynchronous suspension>
           #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #7      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #13     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #16     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #17     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[  +15 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1
```

**Comment by leisim** [comment] 2021-03-27 12:50
Thank you I'll try to reproduce it :)

**Comment by DarkHeros09** [comment] 2021-03-27 12:51
you're welcome, good luck.

**Comment by DarkHeros09** [comment] 2021-03-27 12:54
here's product_color.dart

```
import 'package:equatable/equatable.dart';

class ProductColor extends Equatable {
  final String? hexValue;
  final String? colourName;
  const ProductColor({
    this.hexValue,
    this.colourName,
  });

  @override
  List<Object> get props => [hexValue!, colourName!];
}
```

and product_color_model.dart
```
class ProductColorModel extends ProductColor {
  final String? hexValue;
  final String? colourName;
  const ProductColorModel({
    this.hexValue,
    this.colourName,
  }) : super(hexValue: hexValue, colourName: colourName);

  factory ProductColorModel.fromJson(Map<String, dynamic> json) =>
      _$ProductColorModelFromJson(json);
  Map<String, dynamic> toJson() => _$ProductColorModelToJson(this);
}
```
if you want to reproduce it accurately.

**Comment by leisim** [comment] 2021-03-27 13:01
I think I have found the issue (definitely need to work on error messages): Isar currently does not support final properties. It's something that I have planned but there is still some work to do.

**Comment by DarkHeros09** [comment] 2021-03-27 13:04
> 
> 
> I think I have found the issue (definitely need to work on error messages): Isar currently does not support final properties. It's something that I have planned but there is still some work to do.

Great, glad you figured it out, btw will i be able you use json_serializable along with isar?

**Comment by leisim** [comment] 2021-03-27 13:13
I have not tested that but I definitely intend to support `json_serializable` and `freezed?.

**Comment by Sadmansamee** [comment] 2021-04-02 12:09
I look forward to to json seriazble and Freezed. Really need it @leisim

**Comment by leisim** [comment] 2021-04-02 12:11
@Sadmansamee I'm currently working on query modifiers and aggregation but it will be prioritized after that.

**Comment by tiarebalbi** [comment] 2021-05-27 07:23
```dart 
@Collection()
class Budget {
  @Id()
  int? id;
  late double limit;
  var category = IsarLink<BudgetCategory>();
}
``` 

having the same issue, in this case with Linked collections, the code above fails to compile because of the initialization of `category`. To avoid the error I had to add `@Ignore()`

**Comment by leisim** [comment] 2021-12-31 23:08
Fixed with stable release

**Closed by leisim** 2021-12-31 23:08 UTC
Labels: bug
