### ISSUE TITLE
IsarError: Unsupported processor architecture "linux_arm64"

### ISSUE THREAD

**Issue by Sheppio** [isar/isar#1398] opened 2023-08-18 13:19 UTC
Could you please support linux_arm64?

I have written a server application in Dart but I get the following exception when deploying it as Docker container.  The Docker host is a Raspberry Pi 4 running Ubuntu.

```
Unhandled exception:
IsarError: Unsupported processor architecture "linux_arm64". Please open an issue on GitHub to request it.
#0      _extension#1.localName (package:isar/src/native/isar_core.dart:213)
#1      initializeCoreBinary (package:isar/src/native/isar_core.dart:61)
#2      Isar.initializeIsarCore (package:isar/src/isar.dart:309)
#3      main (file:///app/bin/server.dart:76)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```

**Comment by simc** [comment] 2023-08-21 10:26
Duplicate of #848

**Closed by simc** 2023-08-21 10:26 UTC
Labels: enhancement
