### ISSUE TITLE
Windows app crash when calling isar.clear() (Isar 3.0.X only)

### ISSUE THREAD

**Issue by FredJul** [isar/isar#762] opened 2022-10-10 08:32 UTC
### Steps to Reproduce

Unfortunately I wasn't able to provide a sample app to reproduce it. We have this crash on the professional app we are developing and each time I try to reproduce with another project or a smaller/different data set the crash disappears.

It only crashes on Windows (we tried on several computer and Windows versions), not on the clear call itself but when the transaction closes. Contrary to https://github.com/isar/isar/issues/687 we were not able to reproduce on android/iOS with the exact same data while it 100% reproductible on windows, and it does not crash when we are inserting the data.

It seems to be linked to the data stored in the DB more than the schemes: if the database is empty then calling clear() will not crash.
It seems it was not crashing before we migrated from Isar 2.5.X to 3.0.X.

The only message logged is "Lost connection with device" without any visible stacktraces. Is there a way to display more error output?

### Details

 - Platform: Windows
 - Flutter version: 3.3.4
 - Isar version: 3.0.2

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by DanielLinton** [comment] 2022-10-11 09:35
Are any of your data records over 4kb?  I was having a similar problem, on Windows only, when any of my data records was over 4kb in size. Deleting that record, or clearing the db would cause it to crash with the "Lost connection with device" message.

**Comment by FredJul** [comment] 2022-10-11 19:29
It's a complicated and quite massive dataset, so I wouldn't be surprised at all that one of the data is above 4kb, even if I can't easily check that.

But if what you say is true, then it seems my problem is the same than https://github.com/isar/isar/issues/687 (even if https://github.com/isar/isar/issues/687#issuecomment-1252058675 make me think it was not). I'll try tomorrow to do a sample app with a >4kb record and check if the crash is similar.

**Comment by FredJul** [comment] 2022-10-12 08:28
I managed to reproduce the crash on windows with a data above 4kb. Here is an example app: [testisar.zip](https://github.com/isar/isar/files/9762950/testisar.zip)
You need to press the button at least 2 times to crash on windows (it does not crash on iOS).

**Comment by anandsubbu007** [comment] 2022-10-18 14:48
isar: ^3.0.2
```
thread 'isarworker' panicked at 'range end index 33282 out of range for slice of length 152', library\core\src\slice\index.rs:73:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Lost connection to device.
```

app crash with this.

**Comment by honjow** [comment] 2022-10-22 16:36
I have the same problem, only on windows

**Comment by Hcs66** [comment] 2022-10-24 11:07
I have the same problem (long text stored), on windows.
Isar: 3.0.2
Flutter: 3.3.5
Windows 11

**Comment by KubrickRubrik** [comment] 2022-11-08 04:06
My database has 6 tables. Each table is ~2 megabytes in size. The crash problem is solved by using the **clear** operation for each table in a separate transaction.

**Comment by leisim** [comment] 2022-11-08 12:00
Duplicate of #687

**Closed by leisim** 2022-11-08 12:00 UTC
Labels: needs investigation

**Comment by hiennguyen1001** [comment] 2022-11-14 09:01
> I managed to reproduce the crash on windows with a data above 4kb. Here is an example app: [testisar.zip](https://github.com/isar/isar/files/9762950/testisar.zip) You need to press the button at least 2 times to crash on windows (it does not crash on iOS).

@leisim new version 3.0.3 isn't working on this example

**Comment by leisim** [comment] 2022-11-14 10:30
@hiennguyen1001 yes there was another issue. Fix is already done and I'll release it in a few minutes
