### ISSUE TITLE
Cannot open Environment: MdbxError (75): Value too large for defined data type

### ISSUE THREAD

**Issue by TBoxhead** [isar/isar#1050] opened 2023-01-18 11:16 UTC
### Steps to Reproduce

I am trying to open an isar instance using 
` Isar isarDb = await Isar.open([dbSchema]);`
 and i have also tried 
` final dir = await getApplicationDocumentsDirectory();
  await Isar.open([dbSchema], directory: dir.path);`
and i always get `Cannot open Environment: MdbxError (75): Value too large for defined data type`

I am running on a Pixel 3 emulator with an API level 30, Android 11.0 x86.
I also ran it on an Pixel 3 emulator with an API level 33, Android Tiramisu x86_64 and it works.

Have to mention that i ran both my application and the sample app in the same manner, so on the API level 30 and API level 33 and had the same effect, error for API level 30 and working for API level 33.

### Details

 - Platform: Pixel 3 emulator, API level 30, Android 11.0x86
 - Flutter version: sdk: '>=2.18.6 <3.0.0'
 - Isar version: ^3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by TBoxhead** [comment] 2023-01-18 13:46
I found out that the Android 11.0 x86 doesn't work but the Android 11.0 x86_64 works, same API level. Can someone explain why?

**Comment by SpeedfireV** [comment] 2023-01-21 15:30
I have encountered the same problem and for me it seems to work fine with a real device.

**Comment by lawaiter** [comment] 2023-01-24 16:04
i have the same problem, it works fine with the Android11.0 x86_64, Hope to solve this issue.

**Comment by aspiiire** [comment] 2023-01-30 19:20
I have the same error use 2 different emulators

**Comment by abdullahalamodi** [comment] 2023-02-02 16:03
I have the same error on pixel_3a_api_30_x86 emulator

**Comment by JaffaKetchup** [comment] 2023-02-05 17:47
This appears to be a duplicate of https://github.com/isar/isar/issues/860.

**Comment by simc** [comment] 2023-04-16 10:54
Isar does not support the x86 platform

**Closed by simc** 2023-04-16 10:54 UTC

**Comment by Abolfazl-MI** [comment] 2023-06-02 09:19
even in real device I got this error :-1:

**Comment by lqlam** [comment] 2023-06-15 03:53
> even in real device I got this error 👎
Tested on my device is Pixel 3 with Android 12. it's fine. But emultator is not

**Comment by callmhejerry** [comment] 2023-08-09 21:58
Does it mean that even in real device the error will still occur?

**Comment by callmhejerry** [comment] 2023-08-09 21:58
Does it mean that even in real device the error will still occur?

**Comment by bglassesgirl** [comment] 2024-01-28 23:20
I had the same problem, you just need to hava an API 33 x86_64, and that is it

**Comment by hshasan99** [comment] 2024-06-06 02:58
I have been searching for a solution for the past four days. I am going crazy and want to scream very loudly. I keep encountering the same error on the Pixel_8_API_30_x86 emulator running Android 11.0. I have tried many emulators too.

**Comment by Hamid313-coder** [comment] 2025-01-02 09:13
> **In real device it is working fine.** --> I have been searching for a solution for the past four days. I am going crazy and want to scream very loudly. I keep encountering the same error on the Pixel_8_API_30_x86 emulator running Android 11.0. I have tried many emulators too.

Bro don't scream please!😁.
I think Isar doesn't supports emulator.
BTW we are not going deploy our apps on emulator
