### ISSUE TITLE
Encryption Support

### ISSUE THREAD

**Issue by GQAdonis** [isar/isar#325] opened 2022-04-05 09:58 UTC
**The Issue**
For sensitive data inside mobile applications, encryption of the database itself while maintaining the ability to query is really important. 

**The Potential Solution**
This feature would be a lot like [SQLCipher](https://www.zetetic.net/sqlcipher/) for [SQLite](https://www.sqlite.org/index.html).

**Comment by leisim** [comment] 2022-04-24 05:53
Duplicate of #292

**Closed** 2022-04-24 05:53 UTC
Labels: enhancement
