### ISSUE TITLE
Error with @enumerated migration from 3.0.0 to 3.0.1

### ISSUE THREAD

**Issue by mindblastr** [isar/isar#723] opened 2022-09-26 16:58 UTC
Migrated Isar version from 3.0.0 to 3.0.1. Upgrade flutter packages, run rebuild of isar generated code, build doesn't finish due to error on 2 separate fields with @enumerated.

```
type 'EnumElementImpl' is not a subtype of type 'ClassElement' in type cast
[SEVERE] isar_generator on lib/src/collections/session_rep_collection.dart
```

Going back to 3.0.0 for now.

**Comment by leisim** [comment] 2022-09-26 16:59
Duplicate of #719

**Closed by leisim** 2022-09-26 16:59 UTC
