### ISSUE TITLE
Requested result might be inconsistent with previously returned results

### ISSUE THREAD

**Issue by zonaro** [isar/isar#353] opened 2022-04-25 20:03 UTC
**Steps to Reproduce**
```
flutter clean  
flutter pub get
flutter pub run build_runner build --delete-conflicting-outputs

```
I'm trying to run the build_runner but the following problem occurs

```
[SEVERE] isar_generator:isar_generator on lib/model/veiculos.dart:
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results
```

**veiculos.dart**
```
// ignore_for_file: non_constant_identifier_names

import 'package:isar/isar.dart';

part 'veiculos.g.dart';

@Collection()
class Veiculo {
  @Id()
  int? id;
  String Placa = "";
  String Marca = "";

  Veiculo({
    required this.Placa,
    required this.Marca,
  });

  Veiculo.fromJson(Map<String, dynamic> map) {
    Placa = map['Placa'] ?? "";
    Marca = map['Marca'] ?? "";
  }

  Map<String, dynamic> toMap() {
    return {"Placa": Placa, "Marca": Marca};
  }
}
```

This also happens with other files

**Version**
 - IDE: VSCode 
 - Flutter version: 2.10.5
 - Isar version: ^2.4.0
 - Isar Generator version: ^2.4.0

**Comment by leisim** [comment] 2022-05-14 21:11
I'm unable to reproduce this issue unfortunately. There seem to be reports from different libraries so I don't think this is an Isar issue. Going to close this for now

**Closed by leisim** 2022-05-14 21:11 UTC
