### ISSUE TITLE
androidx.startup.d: java.lang.UnsatisfiedLinkError: dlopen failed: library "libisar.so" not found

### ISSUE THREAD

**Issue by ductranit** [isar/isar#869] opened 2022-11-08 05:36 UTC
### Steps to Reproduce
I got many crashes report from google play and crashlytics:
```
Fatal Exception: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.d: java.lang.UnsatisfiedLinkError: dlopen failed: library "libisar.so" not found
       at android.app.ActivityThread.installProvider(ActivityThread.java:8242)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7728)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7482)
       at android.app.ActivityThread.access$1600(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
It isn't 32 bit issue #367 and it happen on latest isar 3.0.2. But I can't reproduce it on my side.

### Code sample

```dart
  var dir = await getApplicationSupportDirectory();
  final isar = await Isar.open(
    [schemaList],
    directory: dir,
  );
```

### Details

 - Platform:android 8, 10, 12
 - Flutter version: 3.3.7
 ```
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-arm, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.64.0)
[✓] VS Code (version 1.73.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```
 - Isar version: 3.0.2
- Reported devices:
```
  Galaxy A32 5G
  Nexus 5X
  ART-L29
```
---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by leisim** [comment] 2022-11-08 12:25
Duplicate of #849

**Closed by leisim** 2022-11-08 12:25 UTC
