### ISSUE TITLE
Always Crashes on iPhone

### ISSUE THREAD

**Issue by DeanFs** [isar/isar#997] opened 2022-12-21 09:33 UTC
### Issue

It crashes very frequently when used on iPhone. 
Here is the stack message at the time of the crash

### Stack message

```dart
Runner(35676,0x16cd6f000) malloc: *** error for object 0xffffffffffffffff: pointer being freed was not allocated
Runner(35676,0x16cd6f000) malloc: *** set a breakpoint in malloc_error_break to debug
* thread #27, name = 'isarworker', stop reason = signal SIGABRT
    frame #0: 0x00000001fb6d02f4 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1fb6d02f4 <+8>:  b.lo   0x1fb6d0310               ; <+36>
    0x1fb6d02f8 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1fb6d02fc <+16>: mov    x29, sp
    0x1fb6d0300 <+20>: bl     0x1fb6cbcd4               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.
```

### Details

 - Platform: iPhone 8 etc.
 - Flutter version: [e.g. 3.3.10]
 - Isar version: [e.g. 3.0.5]

---

**Comment by simc** [comment] 2022-12-21 09:56
Duplicate of #915

**Closed** 2022-12-21 09:56 UTC
