### ISSUE TITLE
Not working on some android device and android emulator

### ISSUE THREAD

**Issue by caeldev1** [isar/isar#845] opened 2022-10-31 02:50 UTC
### Steps to Reproduce
It worked before but when I moved to another version, it crashes on some devices

flutter 3.3.5
I moved to Isar 3.0.2, and now it doesn't work on ASUS emulator (android-x64) and on devices like Huawei P8 anymore,

### Details

 - Platform: Android Emulator ASUS I001DA (android-x64) and Huawei P8
 - Flutter version: 3.3.5
 - Isar version: 3.0.2

I got this error on the emulator in debug mode:
`I/isarworker( 4104): type=1400 audit(0.0:666): avc: denied { getattr } for path="/mnt/shared/Applications" dev="vboxsf" ino=1 scontext=u:r:untrusted_app:s0:c62,c256,c512,c768 tcontext=u:object_r:unlabeled:s0 tclass=dir permissive=1
F/libc    ( 4104): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 4178 (isarworker), pid 4104 (.example.zbible)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Android/graceltexx/gracelte:9/PQ3A.190705.003/G9700FXXU1APFO:user/release-keys'
Revision: '0'
ABI: 'x86_64'
pid: 4104, tid: 4178, name: isarworker  >>> com.example.zbible <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'range end index 6442343141 out of range for slice of length 141'
    rax 0000000000000000  rbx 0000000000001052  rcx 00007ffff3c68b98  rdx 0000000000000006
    r8  00007ffff3c5f530  r9  00007ffff3c5f530  r10 00007ffff3c5f530  r11 0000000000000246
    r12 00007fff5bfd7e88  r13 0000000000000001  r14 0000000000001008  r15 00007fff51dfc188   
 rdi 0000000000001008  rsi 0000000000001052
    rbp 00007fff522ce188  rsp 00007fff51dfc178  rip 00007ffff3c68b98
backtrace:
    #00 pc 0000000000026b98  /system/lib64/libc.so (syscall+24)
    #01 pc 0000000000029705  /system/lib64/libc.so (abort+101)
    #02 pc 00000000000d13a6  /data/app/com.example.zbible-wzrfSuxo6I_8_tJeyNHf0Q==/lib/x86_64/libisar.so (offset 0x48000)
    #03 pc 00000000000f9b77  /data/app/com.example.zbible-wzrfSuxo6I_8_tJeyNHf0Q==/lib/x86_64/libisar.so (offset 0x48000)
    #04 pc 0000000000007187  [anon:.bss:00007ffff3d37000]
Lost connection to device.'
`

**Comment by leisim** [comment] 2022-11-08 12:56
Duplicate of #727

**Closed by leisim** 2022-11-08 12:56 UTC
