### ISSUE TITLE
IsarError: Cannot open Environment: MdbxError (75): Value too large for defined data type

### ISSUE THREAD

**Issue by 1N50MN14** [isar/isar#589] opened 2022-08-25 16:08 UTC
**Steps to Reproduce**
Isar fails to open and throws the exception `IsarError: Cannot open Environment: MdbxError (75): Value too large for defined data type`. Apologies if I'm missing on something, I'm new to Isar, but I followed the documentation. Code snippet below.

**Code sample**
```
Future<void> main() async
{  
  await runZonedGuarded(() async
  {
     final dir = await getApplicationSupportDirectory();

     final isar = await Isar.open(
      [TestSchema],
      name: 'default',
      directory: dir.path,
    );    
    runApp(Application(isar:isar));
  }, (error, stackTrace) {
    FirebaseCrashlytics.instance.recordError(error, stackTrace, fatal: true);
  });
}
```

```
@Collection()
class Test
{
  //tried changing that to Isar.autoIncrement, didn't help
  final id = Isar.minId; 

  @Index(unique: true)
  late String messageId;

  late int timestamp;

  String? title;

  String? body;
}
```

**Version**
 - Platform: `Android`
 - Flutter version: `3.0.5`
 - Isar version: `3.0.0-dev.10`
 - Isar Generator version: `3.0.0-dev.10`

**Comment by leisim** [comment] 2022-08-25 18:18
Hey, what device do you observe this on? And if it is the simulator, which version and is is it an x86 or x64

**Comment by 1N50MN14** [comment] 2022-08-25 18:39
@leisim x86 emulator (API 30)

**Comment by leisim** [comment] 2022-08-25 18:57
@1N50MN14 Could you please check on a x64 emulator?

**Comment by 1N50MN14** [comment] 2022-08-26 05:40
@leisim I just set up an x64 emulator (API 33 based image) and it ran without issues.

**Comment by 1N50MN14** [comment] 2022-08-26 11:54
Quick follow up, though the app runs on an x64 emulator, Isar prints the following worker `avc: denied` log:

 `W/isarworker( 3812): type=1400 audit(0.0:28): avc: denied { getattr } for path="/linkerconfig" dev="tmpfs" ino=3 scontext=u:r:untrusted_app:s0:c157,c256,c512,c768 tcontext=u:object_r:linkerconfig_file:s0 tclass=dir permissive=0 app: ******`

**Comment by leisim** [comment] 2022-08-26 20:03
@1N50MN14 but does it work?

**Comment by 1N50MN14** [comment] 2022-08-27 02:22
@leisim Yes it does 👍

**Comment by sumanchapai** [comment] 2022-08-29 15:11
I am getting the same error in ios (iphone13 iOS 15.2) simulator. Anyone knows a potential fix?

**Comment by leisim** [comment] 2022-08-29 15:34
@sumanchapai do you have a reproducible example? That would be incredibly helpful.

**Comment by sumanchapai** [comment] 2022-08-30 03:02
Also, I verified that you won't get any errors running this in any emulator 64 bit (x86_64) image. Running in 32 bit (x86) image gives **Value too large for defined data type** error.

**Comment by mrclauss** [comment] 2022-09-04 19:14
I'm also seeing this issue here on x86

**Comment by mrclauss** [comment] 2022-09-07 10:37
Can't reproduce this either right now. In my case it was maybe because of some existing data from -dev8. Plain installation doesn't show this right now.

**Comment by gustavjohansen98** [comment] 2022-09-07 13:52
Hi, I'm having the same issue with x86 Android 11.0 and Isar 3.0.0-dev.14 - it seems like the problem is related to the new (but very nice indeed) enum annotations. I tried with all the new EnumTypes, but the issue remains the same .. 

Any idea how to fix ? :)

**Comment by leisim** [comment] 2022-09-07 14:55
No because I still fail to reproduce it. A small example would be extremely helpful 💜

**Comment by gustavjohansen98** [comment] 2022-09-07 15:08
This is my collection

```
@Collection(inheritance: true)
class AppSettingsModel extends BaseModel {
  @Enumerated(EnumType.name)
  AppThemeEnum selectedTheme;
  
  bool shouldSendLogFiles;

  AppSettingsModel({
    required this.selectedTheme,
    this.shouldSendLogFiles = true,
  });
}
```

The `BaseModel` contains only an id.

I have tried with `EnumType.value`, `EnumType.name` and `EnumType.ordinal` and the error is the same for all three options. If I roll back my Isar version and use the `TypeConverter` everything is fine.

**Comment by gustavjohansen98** [comment] 2022-09-07 15:12
My emulator is x86 Android 11.0 API level 30

**Comment by gustavjohansen98** [comment] 2022-09-07 15:41
Update: Everything is working fine and as expected on Android API 33 x86_64

**Comment by leisim** [comment] 2022-09-07 15:50
I don't really care about the x86 emulator honestly but I would be interested whether anyone sees this issue on 32bit (armv7) Android devices

**Comment by mrclauss** [comment] 2022-09-07 15:53
I will try once my old J3 is charged...

Am 7. September 2022 17:51:09 MESZ schrieb Simon Leier ***@***.***>:
>I don't really care about the x86 emulator honestly but I would be
>interested whether anyone sees this issue on 32bit (armv7) Android
>devices
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/isar/isar/issues/589#issuecomment-1239576515
>You are receiving this because you commented.
>
>Message ID: ***@***.***>

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by mrclauss** [comment] 2022-09-08 05:21
> I will try once my old J3 is charged... Am 7. September 2022 17:51:09 MESZ schrieb Simon Leier ***@***.***>:
> […](#)
> I don't really care about the x86 emulator honestly but I would be interested whether anyone sees this issue on 32bit (armv7) Android devices -- Reply to this email directly or view it on GitHub: [#589 (comment)](https://github.com/isar/isar/issues/589#issuecomment-1239576515) You are receiving this because you commented. Message ID: ***@***.***>
> -- Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

So I tested this, also works as expected on Samsung J3, Lineage OS14 (Android 7.1.2)

**Comment by leisim** [comment] 2022-09-18 09:57
Closing this for now as it only seems to affect certain x86 emulators.

**Closed by leisim** 2022-09-18 09:57 UTC
Labels: needs investigation, area:core

**Comment by sumanchapai** [comment] 2022-09-18 14:35
It also affects ios simulators.
Not sure if that's because they're x86?

**Comment by lKinderBueno** [comment] 2022-09-21 13:22
There is a problem with Android TV emulators. They are only available as x86

**Comment by mrclauss** [comment] 2022-09-21 19:42
So then I would recommend reopening this issue on low priority in order not to forget about this completely...

**Comment by lamarios** [comment] 2024-01-17 04:08
Anyone found a solution to run this on android tv emulators ?
