### ISSUE TITLE
[Inspector] Not deleting items with high ids

### ISSUE THREAD

**Issue by JCKodel** [isar/isar#1146] opened 2023-03-15 23:29 UTC
### Steps to Reproduce

I'm using a function to generate ids based on some hashes and timestamps. For example, some generated id using that function would be 97219924020346450 and 100470080392073400.

Isar Inspector delete button does nothing on those records (although the delete all button works just fine).

### Details

 - Platform: iPhone Simulator
 - Flutter version: 3.7.7
 - Isar version: 3.0.5

---

 - [X] I searched for similar issues already
 - [X] I filled the details section with the exact device model and version
 - [X] I am able to provide a reproducible example

**Comment by markusstephanides** [comment] 2023-06-04 19:43
Bump, since I switched to generated ids using fastHash, like recommended in the documentation, I'm unable to mutate data in the inspector. Reading works fine, but I can't edit, delete or insert data anymore.

**Comment by simc** [comment] 2023-08-16 09:31
Duplicate of #972

**Closed by simc** 2023-08-16 09:31 UTC
