### ISSUE TITLE
isar_flutter_libs_plugin.dll is flagged as infected

### ISSUE THREAD

**Issue by Mangiang** [isar/isar#582] opened 2022-08-24 05:17 UTC
**Steps to Reproduce**
1. Create a new Flutter project
2. Install `isar`, `isar_flutter_libs` and `isar_generator` (no need to even import in dart files)
3. Build and run the application either in Release or Debug mode
4. Notice Bitdefender flagging `isar_flutter_libs_plugin.dll` as infected with `Gen:Variant.Tedy.191473`
![image](https://user-images.githubusercontent.com/9913715/186334897-ff5e7531-8605-4125-b0a1-83a7f81d1eb7.png)

**Code sample**
```yml
name: my_app
description: An example app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  xml: ^5.3.1
  file_picker: ^4.6.1
  path_provider: ^2.0.11
  yaml: ^3.1.1
  crypto: ^3.0.2
  yaml_writer: ^1.0.2
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0

dev_dependencies:
  isar_generator: ^2.5.0
  build_runner: any

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
```

**Version**
 - Platform: Windows
 - Flutter version: 3.0.5
 - Isar version: 2.5.0
 - Isar Generator version: 2.5.0
 - [VirusTotal analysis](https://www.virustotal.com/gui/file/d060fdfb6081ddd3b5d58910d32bbe01befb43a30a641b4b23e7e4b7e6685f0a?nocache=1)

**Comment by leisim** [comment] 2022-08-24 06:05
I've compiled this dll myself and it does not contain any malicious code.
Unfortunately this is a common problem with software virus scanners haven't seen before 😞

**Comment by leisim** [comment] 2022-08-24 07:30
I just ran the latest and the 2.5.0 Isar dll and it does not show any results. I can't reproduce your results.

[Isar 2.5.0 result](https://www.virustotal.com/gui/file/089c7d32f0113cbccf07903c96aabdc9de86f6c3641e3e495a3a333505e12e88)
[Isar 3.0.0-dev.10 result](https://www.virustotal.com/gui/file/762b72242bf3220bab6943b3cd8c9e6a95153aae6907a7e3f848aa2c7735f9cd)

**Comment by Mangiang** [comment] 2022-08-24 14:01
Thank you for taking the time to reproduce the issue !

How strange, I'll try to create a minimal repository and link it here so we have the same source

**Comment by Mangiang** [comment] 2022-08-24 17:59
Here is the [repository](https://github.com/Mangiang/isar_infection_issue) hopefully it can help you reproduce.

**Comment by Mangiang** [comment] 2022-08-25 00:00
I double checked your result and noticed the file you uploaded is named `isar_windows_x64-2.dll`, not `isar_flutter_libs_plugin.dll`, is it the same file ? It doesn't have the same imports as my file either

**Comment by leisim** [comment] 2022-08-25 07:02
But the isar_flutter_libs_plugin depends on your app code. I uploaded Isar Core.

**Comment by Mangiang** [comment] 2022-08-25 12:35
> But the isar_flutter_libs_plugin depends on your app code. I uploaded Isar Core.

Oh I see ! Thank you for the clarification.

Could you have a look at [this repository](https://github.com/Mangiang/isar_infection_issue) and see if you can reproduce the issue ?
It is a **newly created repository**.
Please note:

- I didn't touch anything beside the `pubspec.yaml` so I am almost sure there are no viruses 😅.
- in the `pubspec.yaml` I changed the name, description and  added the three Isar libraries `isar`, `isar_flutter_libs`, `isar_generator`
- if you remove `isar_flutter_libs` there should not be any issue, so I guess `isar_flutter_libs` adds some wrapper or injects code that is flagged as a virus

**Comment by leisim** [comment] 2022-08-25 21:07
Unfortunately I don't think I can fix this since Isar is not doing anything malicious. Going to close this for now.

**Closed by leisim** 2022-08-25 21:07 UTC

**Comment by MerijnHendriks** [comment] 2022-08-25 22:42
I got the same issue as well
