### ISSUE TITLE
Fixed-length List exception for List<String> fields

### ISSUE THREAD

**Issue by zsrclaw** [isar/isar#1444] opened 2023-09-23 11:47 UTC
### Steps to Reproduce

1. Creating a growable List<String> field in the schema.
2. Insert the object into the database.
3. Read it from the database.
4. Try to add a new item into the `List<String>`, and got a fixed-length List expection.

Also got an exception when creating a List with an embedded object. 
But it works with `List<DateTime>`.

### Code sample

```dart
import 'package:isar/isar.dart';

part 'task.g.dart';

@collection
class Task {
  Id id = Isar.autoIncrement;

  List<String> texts = List.empty(growable: true);
  List<DateTime> times = List.empty(growable: true);
}
```

```dart
  final task = Task();
  task.texts.add("one");
  task.times.add(DateTime.now());

  final id = await isar.writeTxn(() async {
    return isar.tasks.put(task);
  });

  final task2 = await isar.tasks.get(id);
  if (task2 != null) {
    task2.times.add(DateTime.now()); // it works
    task2.texts.add("two");     // can't add new item to fixed-length list
  }
```

### Details

 - Platform: x86_64 Android Emulator on Windows
 - Flutter version: 3.13.5
 - Isar version: 3.1.0+1

---

**Comment by sfaletti** [comment] 2023-11-20 13:11
I'm seeing the same issue on the iOS Simulator
- macOS 14.1
- Flutter 3.13.9
- Isar 3.1.0+1

**Comment by mrkaraaslan** [comment] 2023-11-24 11:07
I am having the same issue with `List<Id> Ids`

**Comment by Jtplouffe** [comment] 2023-11-24 12:04
Duplicate of https://github.com/isar/isar/issues/703

**Closed by Jtplouffe** 2023-11-24 12:04 UTC
