### ISSUE TITLE
The integer literal can't be represented exactly in JavaScript.

### ISSUE THREAD

**Issue by ivanesi** [isar/isar#1010] opened 2022-12-28 10:56 UTC
### Steps to Reproduce
When I build the app for Chrome Im getting this:

> Error: The integer literal 1059002862309002494 can't be represented exactly in JavaScript.
> Try changing the literal to something that can be represented in Javascript. In Javascript 1059002862309002496 is the nearest value that can be represented exactly.

It's `id` field in schema below:

### Code sample

```dart

// GENERATED CODE - DO NOT MODIFY BY HAND

const WordSchema = CollectionSchema(
  name: r'words',
  id: -1059002862309002494,

```

### Details

 - Platform: Chrome for Mac
 - Flutter version: [3.3.10]
 - Isar version: [3.0.5]

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by wtus** [comment] 2022-12-28 15:44
same issue

**Comment by RajnishOnly** [comment] 2023-01-01 16:58
same issue

**Comment by simc** [comment] 2023-01-01 17:06
Duplicate of #686

**Closed by simc** 2023-01-01 17:06 UTC
