### ISSUE TITLE
MdbxError(75): Value too large for defined data type.

### ISSUE THREAD

**Issue by Chappie74** [isar/isar#588] opened 2022-08-25 15:48 UTC
**Steps to Reproduce**
I've created a simple class/collection based on the docs for 3.0.0-dev.10 and it throws this error when trying to create an instance. 

![image](https://user-images.githubusercontent.com/21108487/186710998-68de5700-548d-422e-9a29-f9ea4c89c2da.png)

**Code sample**

story.dart
```dart
import 'package:isar/isar.dart';

part 'story.g.dart';

// @JsonSerializable(explicitToJson: true)
@collection
class Story {
  // @JsonKey(ignore: true)
  Id id = Isar.autoIncrement;

  // @JsonKey(name: 'uuid')
  String? uuid;

  // @JsonKey(name: 'name')
  String? name;

  // @JsonKey(name: 'description')
  String? description;

  // @JsonKey(name: 'date_created')
  DateTime? dateCreated;

  // @JsonKey(name: 'date_modified')
  DateTime? dateModified;

Story({
  required this.name,
  this.description = '',
})  : dateCreated = DateTime.now(),
     dateModified = DateTime.now(),
      uuid = const Uuid().v4().toString();

  // factory Story.fromJson(Map<String, dynamic> json) => _$StoryFromJson(json);
  // Map<String, dynamic> toJson() => _$StoryToJson(this);
}

```

isarService.dart (i'm using a state manager to make isar instance available to all my views)
Same thing happens initialising it the normal way without a state manager too.
```dart
import 'package:base_flutter/shared/models/story.dart';
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';

class IsarService {
  late Isar isar;

  IsarService() {
    getApplicationSupportDirectory().then((dir) async {
      isar = await Isar.open(
        [StorySchema],
        directory: dir.path,
      );
    });
  }
}

```

**Version**
 - Platform: android
 - Flutter version: 3.0.5
 - Isar version:  3.0.0-dev.10
 - Isar Generator version:  3.0.0-dev.10

**Comment by leisim** [comment] 2022-08-25 18:17
Hey, what device do you observe this on? And if it is the simulator, which version and is is it an x86 or x64

**Comment by leisim** [comment] 2022-08-25 20:32
Closing this as duplicate of #589

**Closed by leisim** 2022-08-25 20:32 UTC

**Comment by Chappie74** [comment] 2022-08-26 04:59
API 30, x86. I didn't realise this was a dupe. I'll try x64
