### ISSUE TITLE
Crash on iOS first launch. EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by spatialbits** [isar/isar#225] opened 2022-02-08 19:23 UTC
**Steps to Reproduce**
- Fresh install on iOS device.
- Start app.
- When initializing Isar the app crashes.
- Restart app, Isar initializes OK and app runs.
- Same code on Android phones does not encounter the same error.

```
flutter: ╔════════════════════════════════════════╗
flutter: ║          ISAR CONNECT STARTED          ║
flutter: ╟────────────────────────────────────────╢
flutter: ║ Open the Isar Inspector and enter the  ║
flutter: ║ following URL to connect:              ║
flutter: ╟────────────────────────────────────────╢
flutter: ║   ws://127.0.0.1:63430[/XuI7i1fZSD4]()=   ║
flutter: ╚════════════════════════════════════════╝
* thread #24, stop reason = EXC_BAD_ACCESS (code=1, address=0x10cccc000)
    frame #0: 0x00000001c9401934 libsystem_platform.dylib`_platform_memset + 36
libsystem_platform.dylib`_platform_memset:
->  0x1c9401934 <+36>: stnp   x1, x1, [x0]
    0x1c9401938 <+40>: stnp   x1, x1, [x0, #0x10]
    0x1c940193c <+44>: stnp   x1, x1, [x0, #0x20]
    0x1c9401940 <+48>: stnp   x1, x1, [x0, #0x30]
Target 0: (Runner) stopped.
Lost connection to device.
```

**Code sample**
```
  final schemas = [LineSchema, PointSchema];
  final isar = await Isar.open(
    schemas: schemas,
    directory: d.path,
    relaxedDurability: false,
    inspector: kDebugMode,
  );

```

**Version**
 - Platform: iOS: 14.8.1 (iPhone 7), iOS 15.2.1 (iPhone SE 2nd generation), 14.8.1 (iPhone SE 2nd generation)
 - Flutter version: 2.8.1
 - Isar version: 2.1.4
 - Isar Generator version: 2.1.4

**Comment by leisim** [comment] 2022-02-08 19:29
@spatialbits Do you have sample code that reproduces the issue? That would be greatly appreciated 🙂

**Comment by spatialbits** [comment] 2022-02-08 21:38
OK give this a try:
https://github.com/spatialbits/test_isar_crash

This crashes for me on first run. On second run it starts OK.

**Comment by simonpham** [comment] 2022-02-09 05:08
same issue, using Flutter 2.10.0 & device iPhone 12 (iOS 15.3)

**Comment by leisim** [comment] 2022-02-09 08:29
Thanks so much for your help! I cannot reproduce it on my iPhone 13 but I was able to do so on a Browserstack iPhone SE. I'm working on a fix :)

**Comment by leisim** [comment] 2022-02-14 10:00
Found a fix. Waiting for a new libmdbx release!

**Comment by spatialbits** [comment] 2022-02-14 17:04
Nice! 
Found it:
https://github.com/erthink/libmdbx/issues/267
And the fix:
https://github.com/erthink/libmdbx/commit/925a673d57f10ac4bb73652b831cb1ba5aefcdbe

Thanks for looking into it 👍

**Comment by om-ha** [comment] 2022-02-20 20:11
Eagerly waiting for https://github.com/erthink/libmdbx/issues/267 to be merged from `devel` into `master` (0.11.5) 😄😄

**Comment by leisim** [comment] 2022-02-20 20:12
Me too haha

**Comment by spatialbits** [comment] 2022-02-24 00:41
[Fix has landed ](https://github.com/erthink/libmdbx/releases/tag/v0.11.5) :)

**Comment by leisim** [comment] 2022-02-26 12:58
I'm already working on an update. It will also contains some Link improvements (arbitrary queries can now be performed on links)

**Comment by danielkerwin** [comment] 2022-03-25 05:06
@leisim any update on this? we'd like to use Isar but this issue is preventing us from moving forward

**Comment by flocbit** [comment] 2022-03-27 09:06
@leisim All my beta users and myself are experiencing the same issue. After the first crash it is fortunately possible to use the app though. Would be great to see this fixed soon :)

**Comment by wjbladek** [comment] 2022-03-29 07:09
This issue has befallen on me as well. iOS app crashes on the first launch and then works correctly. I wonder if it's enough to fail App Review :)

**Comment by t-kietzmann** [comment] 2022-03-31 17:42
push, nearly the same error:

```
(lldb) 2022-03-31 19:30:13.876761+0200 Runner[1777:602861] Warning: Unable to create restoration in progress marker file
Initialized TensorFlow Lite runtime.
INFO: Initialized TensorFlow Lite runtime.
Connecting to VM Service at ws://127.0.0.1:50875[/1sxI9v5sdCI]()=[/ws]()
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
Runner(1777,0x1709c7000) malloc: *** error for object 0x14e0d0000: pointer being freed was not allocated
Runner(1777,0x1709c7000) malloc: *** set a breakpoint in malloc_error_break to debug
* thread #23, stop reason = signal SIGABRT
    frame #0: 0x00000001bc9b69e8 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1bc9b69e8 <+8>:  b.lo   0x1bc9b6a04               ; <+36>
    0x1bc9b69ec <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1bc9b69f0 <+16>: mov    x29, sp
    0x1bc9b69f4 <+20>: bl     0x1bc9b2670               ; cerror_nocancel
Target 0: (Runner) stopped.
Lost connection to device.
Exited (sigterm)
```

Code:

```
Future<void> initIsar() async {
    final dirPath = (await getApplicationDocumentsDirectory()).path;

    final transactionsDir = Directory('$dirPath/transactions');

    if (!transactionsDir.existsSync()) {
      await transactionsDir.create(recursive: true);
    }

    _isar = await Isar.open(
      schemas: [TransactionSchema],
      directory: '${dirPath}/transactions',
      inspector: true, 
    );
  }
```

**Comment by robban112** [comment] 2022-04-04 12:54
Hi!
@leisim I would like to know the status for this update :)

**Comment by t-kietzmann** [comment] 2022-04-17 09:45
Does anyone have a working fork?

**Comment by flocbit** [comment] 2022-04-18 07:43
Unfortunately I'm already thinking about switching to drift since it appears the project has been (temporarily) abandoned. 

Would have loved to give Isar a try but looking at severe issues like this not being resolved it seems absolutely impossible to release use it in production environments.

**Comment by leisim** [comment] 2022-04-18 11:13
Working on a new release later this week :)

**Comment by flocbit** [comment] 2022-04-18 11:33
@leisim Even though I am very happy about these news, I have to admit that I am skeptical about using Isar in the future.

Please don't get me wrong, I know very well how little time you have as a software developer, because there is always more than enough work to do especially on a project that doesn't make any money.

However in order for the project to be adopted / used reliably, I'd like to suggest the following:

- Add documentation on setup/testing/roadmap etc. so others can help you develop new features and fix bugs
- Find at least one other maintainer who can approve PRs
- Tell us, how much money you need to spend one or two days a week on maintaining and further developing Isar so we have a number we can split up and send you. I'm pretty sure people would pay for a reliable database, at least I would do it :)

Again, I still appreciate your efforts and work very much, but in order to be able to use Isar without worrying about it's future and consequently about my software's future I would need a little more reliability ;)

**Comment by leisim** [comment] 2022-04-18 15:10
Hey @flocbit,

Totally agree with your post! I'll put time into docs to make contributions easier and showcase the future of the project.

I don't think money will fix the issue, I rather hope to attract more frequent and sizeable contributions from the community.

If it helps a little bit, ClickUp is starting to use this project in our app and you'll therefore see much more active development in the future. Especially since I still very much believe that there is no serious database competing with Isar.

**Comment by iBinbro** [comment] 2022-04-18 15:14
> Hey @flocbit,
> 
> Totally agree with your post! I'll put time into docs to make contributions easier and showcase the future of the project.
> 
> I don't think money will fix the issue, I rather hope to attract more frequent and sizeable contributions from the community. I'm also very open to add contributors to the project if anyone is interested.
> 
> If it helps a little bit, ClickUp is starting to use this project in our app and you'll therefore see much more active development in the future. Especially since I still very much believe that there is no serious database competing with Isar.

Thank you very much for providing such an excellent tool. My current project urgently needs to fix this issue. I hope you can arrange time to solve this issue as soon as possible, thank you very much

**Comment by flocbit** [comment] 2022-04-18 19:38
> Hey @flocbit,
> 
> Totally agree with your post! I'll put time into docs to make contributions easier and showcase the future of the project.
> 
> I don't think money will fix the issue, I rather hope to attract more frequent and sizeable contributions from the community. I'm also very open to add contributors to the project if anyone is interested.

I would definitely consider helping out if I know where to start and what to do...

> If it helps a little bit, ClickUp is starting to use this project in our app and you'll therefore see much more active development in the near future. Especially since I still very much believe that there is no serious database competing with Isar.

That sounds indeed very promising! I'll postpone moving to drift for now and wait for the next release then :)

**Comment by robban112** [comment] 2022-04-19 07:20
For those that needs a working fix ASAP. (My team had to)

I've got a working fork of Isar at (branch master):

- https://github.com/robban112/isar-core
- https://github.com/robban112/isar

It took a while for me to figure out the release process, especially since I had to backtrace to a working commit.

**Comment by robban112** [comment] 2022-04-19 07:32
@leisim Would love to be able to contribute! My team absolutely depends on Isar and I really believe in the project.

One thing that would help me atleast (not sure if this applies to everyone) is as @flocbit mentions, documentation about the architecture & how to get started. Would also say that it would be helpful if branches could be more separated with development and release commits.

**Comment by leisim** [comment] 2022-04-19 07:35
@robban112 Thanks for the suggestions, I'll definitely work on those!

I invited @flocbit and you to the org. Hope you don't mind :)

**Comment by ascendedco** [comment] 2022-04-20 07:35
> For those that needs a working fix ASAP. (My team had to)
> 
> I've got a working fork of Isar at (branch master):
> 
> * https://github.com/robban112/isar-core
> * https://github.com/robban112/isar
> 
> It took a while for me to figure out the release process, especially since I had to backtrace to a working commit.

@robban112 Getting build errors when consuming the forked package from git. Do your changes target a specific Dart / Flutter version?

**Comment by robban112** [comment] 2022-04-20 10:53
@ascendedco Using dart 2.16 + flutter version 2.10.5

This is how I integrate directly with the fork:

<img width="383" alt="Screenshot 2022-04-20 at 12 52 03" src="https://user-images.githubusercontent.com/9986686/164215484-21f6092b-864c-4433-8789-c49567c45b87.png">

**Comment by flocbit** [comment] 2022-04-20 12:58
> @robban112 Thanks for the suggestions, I'll definitely work on those!
> 
> I invited @flocbit and you to the org. Hope you don't mind :)

Thanks for the invitation, I hope I can be of some help :)

**Comment by leisim** [comment] 2022-04-24 09:18
Fixed in latest release 👍

**Closed by leisim** 2022-04-24 09:18 UTC
Labels: bug
