### ISSUE TITLE
IsarError: Cannot open Environment: MdbxError (11)

### ISSUE THREAD

**Issue by ductranit** [isar/isar#868] opened 2022-11-08 03:33 UTC
### Steps to Reproduce
I got many report from craslytics
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: IsarError: Cannot open Environment: MdbxError (11): Try again. Error thrown null.
       at FirebaseCrashlytics.recordError(firebase_crashlytics.dart:120)
       at main.<fn>(main.dart:66)
       at CrashReport.executeInZoned.<fn>(crash_report.dart:54)
```

I can't reproduce this issue on my devices.
Here are few reported devices:
Galaxy Note10+
Galaxy A02s
Galaxy A71 5G
skythtek  816TPC
OPPO CPH2273
OPPO CPH2185
Xiaomi Redmi Note 8 Pro
### Code sample
final isar = await Isar.open(
        [schemaList],
        directory: dir,
      );
### Details

 - Platform: android 9, 10, 13
 - Flutter version: 3.3.5
 - Isar version: 3.0.2
---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by leisim** [comment] 2022-11-08 11:56
Unfortunately it's very difficult to help without a way to reproduce the issue. Maybe you find some steps that trigger it.

Do you open multiple Isar instances?

**Comment by leisim** [comment] 2022-11-08 12:10
Duplicate of #570

**Closed by leisim** 2022-11-08 12:10 UTC
Labels: needs more info

**Comment by ductranit** [comment] 2022-11-08 13:38
> Unfortunately it's very difficult to help without a way to reproduce the issue. Maybe you find some steps that trigger it.
> 
> Do you open multiple Isar instances?

I use only one Isar instance in a singleton class

**Comment by dayron9110** [comment] 2023-04-11 20:59
I have this problem using a singleton from the db with get_it

**Comment by iosephmagno** [comment] 2025-01-09 09:32
Is Isar required immediately upon app launch, or can you afford a brief delay? If waiting is an option, here's a possible solution:

- Access Isar through a single instance.
- Introduce a small delay to minimize the impact of the app lifecycle on initialization.
In our case, we store the majority of our data in an SQLite database, using Isar only for a limited subset where fast, in-memory queries are needed. This approach allows us to wait for Isar's initialization without blocking the app's launch.

```
/// Handle isar initialization to workaround issue MdbxError (11)
/// https://github.com/isar/isar/issues/1068
class IsarManager {
  static Isar? _isar;

  static Future<Isar> get instance async {
    // Await a bit to help prevent issue 1068
    await Future.delayed(const Duration(milliseconds: 1000), () {});
    final currentIsar = _isar;
    if (currentIsar != null) {
      _isar = currentIsar;
      return currentIsar;
    }

    final instanceIsar = Isar.getInstance();

    if (instanceIsar != null && instanceIsar.isOpen) {
      await instanceIsar.close();
    }

    final isar = await Isar.open(
    [SeenUserSchema, SessionStoryActionSchema, FailedDownloadedFileSchema],
    directory: PresenceCache.storagePath,
    );

    _isar = isar;
    return _isar!;
  }
```

**Comment by erthink** [comment] 2025-03-15 16:29
// this is copy&paste of my comment to https://github.com/isar/isar/issues/570

I am the main developer and maintainer of `libmdbx` (the key-value storage engine).

It's amazing to me that in 3 years (!) no one has asked me at least a question about this. For more than 5 years, there has been a publicly accessible telegram group, the link to which is on [libmdbx.dqdkfa.ru](https://libmdbx.dqdkfa.ru/) (the project's home site).

At the moment, I am not aware of any error or flaw in libmdbx that could lead to the described issue.

Moreover, the described situation is not a problem. The error code `11` corresponds to the `EAGAIN` system error code, which is routinely returned by the system kernel in a number of situations when some resource is occupied or insufficient (for example, not enough free RAM or a file region is locked).

### From a practical point of view, libmdbx usage scenarios on Android can potentially have the following situations:
1. There is not enough free RAM and/or PTE (page table entries) to map the database into memory.
2. The process previously working with the database has not yet managed to close the database and/or terminate.
In particular, it should be borne in mind that closing the database may require writing some data to the storage medium, which may be a lot in certain operating scenarios and/or non-optimal/non-optimal use of the database.
Such writing may overlap with other activity/load, or require performing maintenance operations (garbage collection, recovery, transfer/copy) at the file system and/or flash memory controller level.
In the rare worst cases, the delay peaks/spikes can be seconds, and when the flash drive is tired, they can take up to tens of seconds.
3. The system resources used on the previous startup are not yet available for use.
Some stages of virtual memory management in the OS kernel are performed on a delayed basis, in lower priority threads, or no more often than a certain pace (once per second).
On Android/iOS, there are more system mechanisms involved, including managing/clearing various kind of system caches, etc.
So, the system kernel/services can return `EAGAIN` when there are no obvious obvious reasons for this.
4. Antiviruses or other similar services can analyze a files mapped in RAM (i.e. a DB in libmdbx case), both before opening and after closing ones. This can happen both synchronously and asynchronously in the background. This can also lead to a temporary lack of RAM or an explicit return of the error EAGAIN when opening, if the last such analysis has not finished yet.
5. The larger the database size, both current and maximum (set in the database geometry), the more RAM and PTA will be required and (therefore) the greater the probability of manifestation of discussed issue.

### As a workaround, I can recommend the following:
1. Captain obvious: The capabilities of libmdbx should be used rationally, especially the modes of operation of the database and the API for explicitly flushing data to storage media.
2. During the termination of an application, close the MDBX database explicitly and as early as possible.
3. In case the `EAGAIN` error when opening a database, try again a reasonable number of times with a short delay (for example, 10 with a pause from 0.01 to 0.1 seconds).

If someone wants to investigate the cause(s) more deeply and/or find better workaround, then I will give the necessary advices/suggestions (mainly get the debugging version from me and enable logging). Please ask me in libmdbx telegram group.

Nonetheless, please use the latest libmdbx release on the origin above, either on [github-mirror](https://github.com/erthink/libmdbx). Ask the maintainers and/or developers of Isar to update libmdbx used and/or contact the maintainers/developers of the bindings used to update the used library, etc.
